-- DraBornGo Google Play UGC moderation guardrails - current safe baseline
-- Amaç: DM / sosyal / arkadaşlık akışına kullanıcı engelleme, kullanıcı/mesaj şikayeti,
-- admin moderasyon kuyruğu ve engellenen kullanıcıdan mesaj / arkadaşlık isteği kesme güvenliği ekler.

create table if not exists public.dkd_social_blocks (
  dkd_id bigint generated by default as identity primary key,
  dkd_blocker_user_id uuid not null references public.dkd_profiles(user_id) on delete cascade,
  dkd_blocked_user_id uuid not null references public.dkd_profiles(user_id) on delete cascade,
  dkd_reason_text text,
  dkd_created_at timestamptz not null default now(),
  constraint dkd_social_blocks_not_self check (dkd_blocker_user_id <> dkd_blocked_user_id)
);

create unique index if not exists dkd_social_blocks_pair_unique_idx
on public.dkd_social_blocks(dkd_blocker_user_id, dkd_blocked_user_id);

create index if not exists dkd_social_blocks_blocker_idx
on public.dkd_social_blocks(dkd_blocker_user_id, dkd_created_at desc);

create index if not exists dkd_social_blocks_blocked_idx
on public.dkd_social_blocks(dkd_blocked_user_id, dkd_created_at desc);

create table if not exists public.dkd_social_reports (
  dkd_id bigint generated by default as identity primary key,
  dkd_reporter_user_id uuid not null references public.dkd_profiles(user_id) on delete cascade,
  dkd_reported_user_id uuid not null references public.dkd_profiles(user_id) on delete cascade,
  dkd_thread_id uuid references public.dkd_dm_threads(id) on delete set null,
  dkd_message_id bigint references public.dkd_dm_messages(id) on delete set null,
  dkd_reason_key text not null default 'dkd_inappropriate_content',
  dkd_detail_text text,
  dkd_status_key text not null default 'dkd_open',
  dkd_admin_note_text text,
  dkd_admin_user_id uuid references public.dkd_profiles(user_id) on delete set null,
  dkd_created_at timestamptz not null default now(),
  dkd_updated_at timestamptz not null default now(),
  dkd_resolved_at timestamptz,
  constraint dkd_social_reports_not_self check (dkd_reporter_user_id <> dkd_reported_user_id),
  constraint dkd_social_reports_status_key_check check (dkd_status_key in ('dkd_open', 'dkd_reviewing', 'dkd_resolved', 'dkd_dismissed')),
  constraint dkd_social_reports_reason_key_check check (char_length(trim(dkd_reason_key)) between 3 and 80),
  constraint dkd_social_reports_detail_len_check check (dkd_detail_text is null or char_length(trim(dkd_detail_text)) <= 1200)
);

create index if not exists dkd_social_reports_status_idx
on public.dkd_social_reports(dkd_status_key, dkd_created_at desc);

create index if not exists dkd_social_reports_reporter_idx
on public.dkd_social_reports(dkd_reporter_user_id, dkd_created_at desc);

create index if not exists dkd_social_reports_reported_idx
on public.dkd_social_reports(dkd_reported_user_id, dkd_created_at desc);

alter table public.dkd_social_blocks enable row level security;
alter table public.dkd_social_reports enable row level security;

drop policy if exists dkd_social_blocks_select_guard on public.dkd_social_blocks;
create policy dkd_social_blocks_select_guard
on public.dkd_social_blocks
for select to authenticated
using (
  auth.uid() = dkd_blocker_user_id
  or auth.uid() = dkd_blocked_user_id
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_social_reports_select_guard on public.dkd_social_reports;
create policy dkd_social_reports_select_guard
on public.dkd_social_reports
for select to authenticated
using (
  auth.uid() = dkd_reporter_user_id
  or coalesce(public.dkd_is_admin(), false)
);

drop policy if exists dkd_social_reports_update_admin_guard on public.dkd_social_reports;
create policy dkd_social_reports_update_admin_guard
on public.dkd_social_reports
for update to authenticated
using (coalesce(public.dkd_is_admin(), false))
with check (coalesce(public.dkd_is_admin(), false));
-- dkd_social_reports tablosu dkd_updated_at kolonunu RPC içinde manuel günceller; eski updated_at tetikleyicisi kullanılmaz.
drop trigger if exists dkd_social_reports_updated_at_trigger on public.dkd_social_reports;

create or replace function public.dkd_social_is_blocked(
  dkd_param_source_user_id uuid,
  dkd_param_target_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.dkd_social_blocks dkd_block_row
    where (
      dkd_block_row.dkd_blocker_user_id = dkd_param_source_user_id
      and dkd_block_row.dkd_blocked_user_id = dkd_param_target_user_id
    ) or (
      dkd_block_row.dkd_blocker_user_id = dkd_param_target_user_id
      and dkd_block_row.dkd_blocked_user_id = dkd_param_source_user_id
    )
  );
$$;

revoke all on function public.dkd_social_is_blocked(uuid, uuid) from public;
grant execute on function public.dkd_social_is_blocked(uuid, uuid) to authenticated, service_role;

create or replace function public.dkd_social_block_user(
  dkd_param_target_user_id uuid,
  dkd_param_reason_text text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_current_user_id uuid := auth.uid();
  dkd_target_exists_value boolean := false;
  dkd_low_user_id uuid;
  dkd_high_user_id uuid;
  dkd_removed_friendship_count integer := 0;
  dkd_closed_request_count integer := 0;
begin
  if dkd_current_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  if dkd_param_target_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'target_not_found');
  end if;

  if dkd_param_target_user_id = dkd_current_user_id then
    return jsonb_build_object('ok', false, 'reason', 'cannot_block_self');
  end if;

  select exists (
    select 1
    from public.dkd_profiles dkd_profile_row
    where dkd_profile_row.user_id = dkd_param_target_user_id
  ) into dkd_target_exists_value;

  if dkd_target_exists_value is not true then
    return jsonb_build_object('ok', false, 'reason', 'target_not_found');
  end if;

  insert into public.dkd_social_blocks (
    dkd_blocker_user_id,
    dkd_blocked_user_id,
    dkd_reason_text,
    dkd_created_at
  ) values (
    dkd_current_user_id,
    dkd_param_target_user_id,
    nullif(trim(coalesce(dkd_param_reason_text, '')), ''),
    now()
  )
  on conflict (dkd_blocker_user_id, dkd_blocked_user_id) do update
    set dkd_reason_text = excluded.dkd_reason_text,
        dkd_created_at = now();

  update public.dkd_friend_requests dkd_request_row
  set status = 'canceled',
      responded_at = now()
  where dkd_request_row.status = 'pending'
    and (
      (dkd_request_row.requester_id = dkd_current_user_id and dkd_request_row.addressee_id = dkd_param_target_user_id)
      or (dkd_request_row.requester_id = dkd_param_target_user_id and dkd_request_row.addressee_id = dkd_current_user_id)
    );

  get diagnostics dkd_closed_request_count = row_count;

  dkd_low_user_id := case when dkd_current_user_id::text < dkd_param_target_user_id::text then dkd_current_user_id else dkd_param_target_user_id end;
  dkd_high_user_id := case when dkd_current_user_id::text < dkd_param_target_user_id::text then dkd_param_target_user_id else dkd_current_user_id end;

  delete from public.dkd_friendships dkd_friendship_row
  where dkd_friendship_row.user_low = dkd_low_user_id
    and dkd_friendship_row.user_high = dkd_high_user_id;

  get diagnostics dkd_removed_friendship_count = row_count;

  return jsonb_build_object(
    'ok', true,
    'reason', 'blocked',
    'dkd_closed_request_count', dkd_closed_request_count,
    'dkd_removed_friendship_count', dkd_removed_friendship_count
  );
end;
$$;

revoke all on function public.dkd_social_block_user(uuid, text) from public;
grant execute on function public.dkd_social_block_user(uuid, text) to authenticated;

create or replace function public.dkd_social_unblock_user(dkd_param_target_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_current_user_id uuid := auth.uid();
  dkd_deleted_count integer := 0;
begin
  if dkd_current_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  delete from public.dkd_social_blocks dkd_block_row
  where dkd_block_row.dkd_blocker_user_id = dkd_current_user_id
    and dkd_block_row.dkd_blocked_user_id = dkd_param_target_user_id;

  get diagnostics dkd_deleted_count = row_count;

  return jsonb_build_object('ok', true, 'reason', 'unblocked', 'dkd_deleted_count', dkd_deleted_count);
end;
$$;

revoke all on function public.dkd_social_unblock_user(uuid) from public;
grant execute on function public.dkd_social_unblock_user(uuid) to authenticated;

create or replace function public.dkd_social_report_user(
  dkd_param_target_user_id uuid,
  dkd_param_reason_key text default 'dkd_inappropriate_content',
  dkd_param_detail_text text default null,
  dkd_param_thread_id uuid default null,
  dkd_param_message_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_current_user_id uuid := auth.uid();
  dkd_target_exists_value boolean := false;
  dkd_report_id_value bigint;
  dkd_clean_reason_key text := lower(regexp_replace(coalesce(nullif(trim(dkd_param_reason_key), ''), 'dkd_inappropriate_content'), '[^a-z0-9_]+', '_', 'g'));
  dkd_clean_detail_text text := nullif(trim(coalesce(dkd_param_detail_text, '')), '');
begin
  if dkd_current_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  if dkd_param_target_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'target_not_found');
  end if;

  if dkd_param_target_user_id = dkd_current_user_id then
    return jsonb_build_object('ok', false, 'reason', 'cannot_report_self');
  end if;

  if char_length(dkd_clean_reason_key) < 3 then
    dkd_clean_reason_key := 'dkd_inappropriate_content';
  end if;

  if dkd_clean_detail_text is not null and char_length(dkd_clean_detail_text) > 1200 then
    dkd_clean_detail_text := left(dkd_clean_detail_text, 1200);
  end if;

  select exists (
    select 1
    from public.dkd_profiles dkd_profile_row
    where dkd_profile_row.user_id = dkd_param_target_user_id
  ) into dkd_target_exists_value;

  if dkd_target_exists_value is not true then
    return jsonb_build_object('ok', false, 'reason', 'target_not_found');
  end if;

  insert into public.dkd_social_reports (
    dkd_reporter_user_id,
    dkd_reported_user_id,
    dkd_thread_id,
    dkd_message_id,
    dkd_reason_key,
    dkd_detail_text,
    dkd_status_key
  ) values (
    dkd_current_user_id,
    dkd_param_target_user_id,
    dkd_param_thread_id,
    dkd_param_message_id,
    dkd_clean_reason_key,
    dkd_clean_detail_text,
    'dkd_open'
  )
  returning dkd_id into dkd_report_id_value;

  return jsonb_build_object('ok', true, 'reason', 'reported', 'dkd_report_id', dkd_report_id_value);
end;
$$;

revoke all on function public.dkd_social_report_user(uuid, text, text, uuid, bigint) from public;
grant execute on function public.dkd_social_report_user(uuid, text, text, uuid, bigint) to authenticated;

create or replace function public.dkd_social_search_profiles(dkd_param_query text, dkd_param_limit integer default 12)
returns table (
  user_id uuid,
  ally_id bigint,
  nickname text,
  avatar_emoji text,
  level integer,
  rank_key text,
  is_friend boolean,
  pending_sent boolean,
  pending_received boolean,
  request_id bigint
)
language sql
security definer
set search_path = public
stable
as $$
  with dkd_current_user_query as (
    select
      auth.uid() as dkd_current_user_id,
      regexp_replace(coalesce(trim(dkd_param_query), ''), '[^0-9]', '', 'g') as dkd_digits_text,
      lower(coalesce(trim(dkd_param_query), '')) as dkd_query_text
  )
  select
    dkd_profile_row.user_id,
    dkd_profile_row.ally_id,
    coalesce(nullif(trim(dkd_profile_row.nickname), ''), 'Oyuncu') as nickname,
    coalesce(nullif(trim(dkd_profile_row.avatar_emoji), ''), '🦅') as avatar_emoji,
    coalesce(dkd_profile_row.level, 1) as level,
    coalesce(dkd_profile_row.rank_key, 'rookie') as rank_key,
    exists (
      select 1
      from public.dkd_friendships dkd_friendship_row
      where (dkd_friendship_row.user_low = dkd_profile_row.user_id and dkd_friendship_row.user_high = (select dkd_current_user_id from dkd_current_user_query))
         or (dkd_friendship_row.user_high = dkd_profile_row.user_id and dkd_friendship_row.user_low = (select dkd_current_user_id from dkd_current_user_query))
    ) as is_friend,
    exists (
      select 1
      from public.dkd_friend_requests dkd_request_row
      where dkd_request_row.requester_id = (select dkd_current_user_id from dkd_current_user_query)
        and dkd_request_row.addressee_id = dkd_profile_row.user_id
        and dkd_request_row.status = 'pending'
    ) as pending_sent,
    exists (
      select 1
      from public.dkd_friend_requests dkd_request_row
      where dkd_request_row.requester_id = dkd_profile_row.user_id
        and dkd_request_row.addressee_id = (select dkd_current_user_id from dkd_current_user_query)
        and dkd_request_row.status = 'pending'
    ) as pending_received,
    (
      select dkd_request_row.id
      from public.dkd_friend_requests dkd_request_row
      where dkd_request_row.requester_id = dkd_profile_row.user_id
        and dkd_request_row.addressee_id = (select dkd_current_user_id from dkd_current_user_query)
        and dkd_request_row.status = 'pending'
      order by dkd_request_row.created_at desc
      limit 1
    ) as request_id
  from public.dkd_profiles dkd_profile_row
  cross join dkd_current_user_query
  where dkd_current_user_query.dkd_current_user_id is not null
    and dkd_profile_row.user_id <> dkd_current_user_query.dkd_current_user_id
    and coalesce(trim(dkd_param_query), '') <> ''
    and public.dkd_social_is_blocked(dkd_current_user_query.dkd_current_user_id, dkd_profile_row.user_id) is false
    and (
      (dkd_current_user_query.dkd_digits_text <> '' and dkd_profile_row.ally_id::text = dkd_current_user_query.dkd_digits_text)
      or lower(coalesce(dkd_profile_row.nickname, '')) like ('%' || dkd_current_user_query.dkd_query_text || '%')
    )
  order by
    case when dkd_current_user_query.dkd_digits_text <> '' and dkd_profile_row.ally_id::text = dkd_current_user_query.dkd_digits_text then 0 else 1 end,
    case when lower(coalesce(dkd_profile_row.nickname, '')) = dkd_current_user_query.dkd_query_text then 0 else 1 end,
    dkd_profile_row.level desc,
    dkd_profile_row.updated_at desc
  limit greatest(1, least(coalesce(dkd_param_limit, 12), 20));
$$;

revoke all on function public.dkd_social_search_profiles(text, integer) from public;
grant execute on function public.dkd_social_search_profiles(text, integer) to authenticated;

create or replace function public.dkd_social_send_friend_request(dkd_param_target_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_current_user_id uuid := auth.uid();
  dkd_low_user_id uuid;
  dkd_high_user_id uuid;
  dkd_target_exists_value boolean := false;
  dkd_friendship_id_value bigint;
  dkd_request_id_value bigint;
begin
  if dkd_current_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  if dkd_param_target_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'target_not_found');
  end if;

  if dkd_param_target_user_id = dkd_current_user_id then
    return jsonb_build_object('ok', false, 'reason', 'cannot_friend_self');
  end if;

  select exists (
    select 1
    from public.dkd_profiles dkd_profile_row
    where dkd_profile_row.user_id = dkd_param_target_user_id
  ) into dkd_target_exists_value;

  if dkd_target_exists_value is not true then
    return jsonb_build_object('ok', false, 'reason', 'target_not_found');
  end if;

  insert into public.dkd_profiles (user_id) values (dkd_current_user_id) on conflict (user_id) do nothing;

  if public.dkd_social_is_blocked(dkd_current_user_id, dkd_param_target_user_id) then
    return jsonb_build_object('ok', false, 'reason', 'blocked_relationship');
  end if;

  dkd_low_user_id := case when dkd_current_user_id::text < dkd_param_target_user_id::text then dkd_current_user_id else dkd_param_target_user_id end;
  dkd_high_user_id := case when dkd_current_user_id::text < dkd_param_target_user_id::text then dkd_param_target_user_id else dkd_current_user_id end;

  select dkd_friendship_row.id into dkd_friendship_id_value
  from public.dkd_friendships dkd_friendship_row
  where dkd_friendship_row.user_low = dkd_low_user_id
    and dkd_friendship_row.user_high = dkd_high_user_id
  limit 1;

  if dkd_friendship_id_value is not null then
    return jsonb_build_object('ok', false, 'reason', 'friend_exists');
  end if;

  select dkd_request_row.id into dkd_request_id_value
  from public.dkd_friend_requests dkd_request_row
  where dkd_request_row.requester_id = dkd_param_target_user_id
    and dkd_request_row.addressee_id = dkd_current_user_id
    and dkd_request_row.status = 'pending'
  order by dkd_request_row.created_at desc
  limit 1;

  if dkd_request_id_value is not null then
    perform public.dkd_social_respond_friend_request(dkd_request_id_value, 'accept');
    return jsonb_build_object('ok', true, 'reason', 'accepted_existing');
  end if;

  select dkd_request_row.id into dkd_request_id_value
  from public.dkd_friend_requests dkd_request_row
  where dkd_request_row.requester_id = dkd_current_user_id
    and dkd_request_row.addressee_id = dkd_param_target_user_id
    and dkd_request_row.status = 'pending'
  order by dkd_request_row.created_at desc
  limit 1;

  if dkd_request_id_value is not null then
    return jsonb_build_object('ok', false, 'reason', 'request_exists');
  end if;

  insert into public.dkd_friend_requests (requester_id, addressee_id, status)
  values (dkd_current_user_id, dkd_param_target_user_id, 'pending');

  return jsonb_build_object('ok', true, 'reason', 'request_sent');
end;
$$;

revoke all on function public.dkd_social_send_friend_request(uuid) from public;
grant execute on function public.dkd_social_send_friend_request(uuid) to authenticated;

create or replace function public.dkd_social_respond_friend_request(dkd_param_request_id bigint, dkd_param_action text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_current_user_id uuid := auth.uid();
  dkd_request_row public.dkd_friend_requests%rowtype;
  dkd_low_user_id uuid;
  dkd_high_user_id uuid;
  dkd_friendship_id_value bigint;
  dkd_thread_id_value uuid;
  dkd_action_key text := lower(coalesce(trim(dkd_param_action), 'accept'));
begin
  if dkd_current_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  select * into dkd_request_row
  from public.dkd_friend_requests
  where id = dkd_param_request_id
  limit 1;

  if dkd_request_row.id is null then
    return jsonb_build_object('ok', false, 'reason', 'request_not_found');
  end if;

  if dkd_request_row.addressee_id <> dkd_current_user_id then
    return jsonb_build_object('ok', false, 'reason', 'not_request_target');
  end if;

  if dkd_request_row.status <> 'pending' then
    return jsonb_build_object('ok', false, 'reason', 'request_closed');
  end if;

  if dkd_action_key not in ('accept', 'reject') then
    return jsonb_build_object('ok', false, 'reason', 'invalid_action');
  end if;

  if dkd_action_key = 'accept' and public.dkd_social_is_blocked(dkd_current_user_id, dkd_request_row.requester_id) then
    update public.dkd_friend_requests
    set status = 'canceled',
        responded_at = now()
    where id = dkd_request_row.id;

    return jsonb_build_object('ok', false, 'reason', 'blocked_relationship');
  end if;

  update public.dkd_friend_requests
  set status = case when dkd_action_key = 'accept' then 'accepted' else 'rejected' end,
      responded_at = now()
  where id = dkd_request_row.id;

  if dkd_action_key = 'reject' then
    return jsonb_build_object('ok', true, 'reason', 'rejected');
  end if;

  dkd_low_user_id := case when dkd_request_row.requester_id::text < dkd_request_row.addressee_id::text then dkd_request_row.requester_id else dkd_request_row.addressee_id end;
  dkd_high_user_id := case when dkd_request_row.requester_id::text < dkd_request_row.addressee_id::text then dkd_request_row.addressee_id else dkd_request_row.requester_id end;

  insert into public.dkd_friendships (user_low, user_high, created_by)
  values (dkd_low_user_id, dkd_high_user_id, dkd_current_user_id)
  on conflict (user_low, user_high) do nothing;

  select id into dkd_friendship_id_value
  from public.dkd_friendships
  where user_low = dkd_low_user_id
    and user_high = dkd_high_user_id
  limit 1;

  insert into public.dkd_dm_threads (friendship_id, last_message_text, last_message_at)
  values (dkd_friendship_id_value, null, null)
  on conflict (friendship_id) do nothing;

  select id into dkd_thread_id_value
  from public.dkd_dm_threads
  where friendship_id = dkd_friendship_id_value
  limit 1;

  update public.dkd_friend_requests
  set status = 'canceled',
      responded_at = now()
  where requester_id = dkd_request_row.addressee_id
    and addressee_id = dkd_request_row.requester_id
    and status = 'pending';

  return jsonb_build_object('ok', true, 'reason', 'accepted', 'thread_id', dkd_thread_id_value);
end;
$$;

revoke all on function public.dkd_social_respond_friend_request(bigint, text) from public;
grant execute on function public.dkd_social_respond_friend_request(bigint, text) to authenticated;

create or replace function public.dkd_social_get_or_create_thread(dkd_param_friend_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_current_user_id uuid := auth.uid();
  dkd_low_user_id uuid;
  dkd_high_user_id uuid;
  dkd_friendship_id_value bigint;
  dkd_thread_id_value uuid;
begin
  if dkd_current_user_id is null then
    raise exception 'auth_required';
  end if;

  if public.dkd_social_is_blocked(dkd_current_user_id, dkd_param_friend_user_id) then
    raise exception 'blocked_relationship';
  end if;

  dkd_low_user_id := case when dkd_current_user_id::text < dkd_param_friend_user_id::text then dkd_current_user_id else dkd_param_friend_user_id end;
  dkd_high_user_id := case when dkd_current_user_id::text < dkd_param_friend_user_id::text then dkd_param_friend_user_id else dkd_current_user_id end;

  select id into dkd_friendship_id_value
  from public.dkd_friendships
  where user_low = dkd_low_user_id
    and user_high = dkd_high_user_id
  limit 1;

  if dkd_friendship_id_value is null then
    raise exception 'friendship_not_found';
  end if;

  insert into public.dkd_dm_threads (friendship_id)
  values (dkd_friendship_id_value)
  on conflict (friendship_id) do nothing;

  select id into dkd_thread_id_value
  from public.dkd_dm_threads
  where friendship_id = dkd_friendship_id_value
  limit 1;

  return dkd_thread_id_value;
end;
$$;

revoke all on function public.dkd_social_get_or_create_thread(uuid) from public;
grant execute on function public.dkd_social_get_or_create_thread(uuid) to authenticated;

create or replace function public.dkd_social_send_message(dkd_param_thread_id uuid, dkd_param_body text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_current_user_id uuid := auth.uid();
  dkd_allowed_value boolean := false;
  dkd_other_user_id uuid;
  dkd_message_text text := trim(coalesce(dkd_param_body, ''));
begin
  if dkd_current_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  if dkd_message_text = '' then
    return jsonb_build_object('ok', false, 'reason', 'message_empty');
  end if;

  select
    true,
    case when dkd_friendship_row.user_low = dkd_current_user_id then dkd_friendship_row.user_high else dkd_friendship_row.user_low end
  into dkd_allowed_value, dkd_other_user_id
  from public.dkd_dm_threads dkd_thread_row
  join public.dkd_friendships dkd_friendship_row on dkd_friendship_row.id = dkd_thread_row.friendship_id
  where dkd_thread_row.id = dkd_param_thread_id
    and (dkd_friendship_row.user_low = dkd_current_user_id or dkd_friendship_row.user_high = dkd_current_user_id)
  limit 1;

  if coalesce(dkd_allowed_value, false) is not true or dkd_other_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'thread_forbidden');
  end if;

  if public.dkd_social_is_blocked(dkd_current_user_id, dkd_other_user_id) then
    return jsonb_build_object('ok', false, 'reason', 'blocked_relationship');
  end if;

  insert into public.dkd_dm_messages (thread_id, sender_id, body)
  values (dkd_param_thread_id, dkd_current_user_id, dkd_message_text);

  update public.dkd_dm_threads
  set last_message_text = left(dkd_message_text, 120),
      last_message_at = now(),
      updated_at = now()
  where id = dkd_param_thread_id;

  update public.dkd_profiles
  set social_last_seen_at = now(),
      social_status = 'online'
  where user_id = dkd_current_user_id;

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.dkd_social_send_message(uuid, text) from public;
grant execute on function public.dkd_social_send_message(uuid, text) to authenticated;

create or replace function public.dkd_social_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_current_user_id uuid := auth.uid();
  dkd_payload_value jsonb;
begin
  if dkd_current_user_id is null then
    return jsonb_build_object(
      'myProfile', null,
      'friends', '[]'::jsonb,
      'incoming', '[]'::jsonb,
      'outgoing', '[]'::jsonb
    );
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_current_user_id)
  on conflict (user_id) do nothing;

  update public.dkd_profiles
  set social_last_seen_at = now(),
      social_status = 'online'
  where user_id = dkd_current_user_id;

  with dkd_my_profile_rows as (
    select
      dkd_profile_row.user_id,
      dkd_profile_row.ally_id,
      coalesce(nullif(trim(dkd_profile_row.nickname), ''), 'Oyuncu') as nickname,
      coalesce(nullif(trim(dkd_profile_row.avatar_emoji), ''), '🦅') as avatar_emoji,
      coalesce(dkd_profile_row.level, 1) as level,
      coalesce(dkd_profile_row.rank_key, 'rookie') as rank_key,
      dkd_profile_row.social_status,
      dkd_profile_row.social_last_seen_at
    from public.dkd_profiles dkd_profile_row
    where dkd_profile_row.user_id = dkd_current_user_id
    limit 1
  ),
  dkd_friend_rows as (
    select
      dkd_friendship_row.id as friendship_id,
      dkd_other_profile_row.user_id,
      dkd_other_profile_row.ally_id,
      coalesce(nullif(trim(dkd_other_profile_row.nickname), ''), 'Oyuncu') as nickname,
      coalesce(nullif(trim(dkd_other_profile_row.avatar_emoji), ''), '🦅') as avatar_emoji,
      coalesce(dkd_other_profile_row.level, 1) as level,
      coalesce(dkd_other_profile_row.rank_key, 'rookie') as rank_key,
      dkd_other_profile_row.social_status,
      dkd_other_profile_row.social_last_seen_at,
      dkd_thread_row.id as thread_id,
      dkd_thread_row.last_message_text,
      dkd_thread_row.last_message_at,
      dkd_friendship_row.created_at as friend_since,
      coalesce((
        select count(*)::integer
        from public.dkd_dm_messages dkd_message_row
        where dkd_message_row.thread_id = dkd_thread_row.id
          and dkd_message_row.sender_id <> dkd_current_user_id
          and dkd_message_row.seen_at is null
      ), 0) as unread_count
    from public.dkd_friendships dkd_friendship_row
    join public.dkd_profiles dkd_other_profile_row
      on dkd_other_profile_row.user_id = case when dkd_friendship_row.user_low = dkd_current_user_id then dkd_friendship_row.user_high else dkd_friendship_row.user_low end
    left join public.dkd_dm_threads dkd_thread_row on dkd_thread_row.friendship_id = dkd_friendship_row.id
    where (dkd_friendship_row.user_low = dkd_current_user_id or dkd_friendship_row.user_high = dkd_current_user_id)
      and public.dkd_social_is_blocked(dkd_current_user_id, dkd_other_profile_row.user_id) is false
    order by coalesce(dkd_thread_row.last_message_at, dkd_friendship_row.created_at) desc, dkd_other_profile_row.nickname asc
  ),
  dkd_incoming_rows as (
    select
      dkd_request_row.id as request_id,
      dkd_sender_profile_row.user_id,
      dkd_sender_profile_row.ally_id,
      coalesce(nullif(trim(dkd_sender_profile_row.nickname), ''), 'Oyuncu') as nickname,
      coalesce(nullif(trim(dkd_sender_profile_row.avatar_emoji), ''), '🦅') as avatar_emoji,
      coalesce(dkd_sender_profile_row.level, 1) as level,
      coalesce(dkd_sender_profile_row.rank_key, 'rookie') as rank_key,
      dkd_sender_profile_row.social_status,
      dkd_sender_profile_row.social_last_seen_at,
      dkd_request_row.created_at
    from public.dkd_friend_requests dkd_request_row
    join public.dkd_profiles dkd_sender_profile_row on dkd_sender_profile_row.user_id = dkd_request_row.requester_id
    where dkd_request_row.addressee_id = dkd_current_user_id
      and dkd_request_row.status = 'pending'
      and public.dkd_social_is_blocked(dkd_current_user_id, dkd_sender_profile_row.user_id) is false
    order by dkd_request_row.created_at desc
  ),
  dkd_outgoing_rows as (
    select
      dkd_request_row.id as request_id,
      dkd_receiver_profile_row.user_id,
      dkd_receiver_profile_row.ally_id,
      coalesce(nullif(trim(dkd_receiver_profile_row.nickname), ''), 'Oyuncu') as nickname,
      coalesce(nullif(trim(dkd_receiver_profile_row.avatar_emoji), ''), '🦅') as avatar_emoji,
      coalesce(dkd_receiver_profile_row.level, 1) as level,
      coalesce(dkd_receiver_profile_row.rank_key, 'rookie') as rank_key,
      dkd_receiver_profile_row.social_status,
      dkd_receiver_profile_row.social_last_seen_at,
      dkd_request_row.created_at
    from public.dkd_friend_requests dkd_request_row
    join public.dkd_profiles dkd_receiver_profile_row on dkd_receiver_profile_row.user_id = dkd_request_row.addressee_id
    where dkd_request_row.requester_id = dkd_current_user_id
      and dkd_request_row.status = 'pending'
      and public.dkd_social_is_blocked(dkd_current_user_id, dkd_receiver_profile_row.user_id) is false
    order by dkd_request_row.created_at desc
  )
  select jsonb_build_object(
    'myProfile', coalesce((select to_jsonb(dkd_my_profile_rows) from dkd_my_profile_rows), 'null'::jsonb),
    'friends', coalesce((select jsonb_agg(to_jsonb(dkd_friend_rows)) from dkd_friend_rows), '[]'::jsonb),
    'incoming', coalesce((select jsonb_agg(to_jsonb(dkd_incoming_rows)) from dkd_incoming_rows), '[]'::jsonb),
    'outgoing', coalesce((select jsonb_agg(to_jsonb(dkd_outgoing_rows)) from dkd_outgoing_rows), '[]'::jsonb)
  ) into dkd_payload_value;

  return coalesce(dkd_payload_value, jsonb_build_object(
    'myProfile', null,
    'friends', '[]'::jsonb,
    'incoming', '[]'::jsonb,
    'outgoing', '[]'::jsonb
  ));
end;
$$;

revoke all on function public.dkd_social_snapshot() from public;
grant execute on function public.dkd_social_snapshot() to authenticated;

create or replace function public.dkd_social_admin_moderation_queue(
  dkd_param_status_key text default 'dkd_open',
  dkd_param_limit integer default 80
)
returns table (
  dkd_id bigint,
  dkd_status_key text,
  dkd_reason_key text,
  dkd_detail_text text,
  dkd_thread_id uuid,
  dkd_message_id bigint,
  dkd_reporter_user_id uuid,
  dkd_reporter_ally_id bigint,
  dkd_reporter_nickname text,
  dkd_reported_user_id uuid,
  dkd_reported_ally_id bigint,
  dkd_reported_nickname text,
  dkd_admin_note_text text,
  dkd_created_at timestamptz,
  dkd_updated_at timestamptz,
  dkd_resolved_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_clean_status_key text := coalesce(nullif(trim(dkd_param_status_key), ''), 'dkd_open');
begin
  if coalesce(public.dkd_is_admin(), false) is not true then
    raise exception 'admin_required';
  end if;

  return query
  select
    dkd_report_row.dkd_id,
    dkd_report_row.dkd_status_key,
    dkd_report_row.dkd_reason_key,
    dkd_report_row.dkd_detail_text,
    dkd_report_row.dkd_thread_id,
    dkd_report_row.dkd_message_id,
    dkd_report_row.dkd_reporter_user_id,
    dkd_reporter_profile_row.ally_id as dkd_reporter_ally_id,
    coalesce(nullif(trim(dkd_reporter_profile_row.nickname), ''), 'Oyuncu') as dkd_reporter_nickname,
    dkd_report_row.dkd_reported_user_id,
    dkd_reported_profile_row.ally_id as dkd_reported_ally_id,
    coalesce(nullif(trim(dkd_reported_profile_row.nickname), ''), 'Oyuncu') as dkd_reported_nickname,
    dkd_report_row.dkd_admin_note_text,
    dkd_report_row.dkd_created_at,
    dkd_report_row.dkd_updated_at,
    dkd_report_row.dkd_resolved_at
  from public.dkd_social_reports dkd_report_row
  left join public.dkd_profiles dkd_reporter_profile_row on dkd_reporter_profile_row.user_id = dkd_report_row.dkd_reporter_user_id
  left join public.dkd_profiles dkd_reported_profile_row on dkd_reported_profile_row.user_id = dkd_report_row.dkd_reported_user_id
  where dkd_clean_status_key = 'dkd_all'
     or dkd_report_row.dkd_status_key = dkd_clean_status_key
  order by dkd_report_row.dkd_created_at desc
  limit greatest(1, least(coalesce(dkd_param_limit, 80), 200));
end;
$$;

revoke all on function public.dkd_social_admin_moderation_queue(text, integer) from public;
grant execute on function public.dkd_social_admin_moderation_queue(text, integer) to authenticated, service_role;

create or replace function public.dkd_social_admin_update_report_status(
  dkd_param_report_id bigint,
  dkd_param_status_key text,
  dkd_param_admin_note_text text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_current_admin_user_id uuid := auth.uid();
  dkd_clean_status_key text := coalesce(nullif(trim(dkd_param_status_key), ''), 'dkd_reviewing');
  dkd_updated_count integer := 0;
begin
  if coalesce(public.dkd_is_admin(), false) is not true then
    return jsonb_build_object('ok', false, 'reason', 'admin_required');
  end if;

  if dkd_clean_status_key not in ('dkd_open', 'dkd_reviewing', 'dkd_resolved', 'dkd_dismissed') then
    return jsonb_build_object('ok', false, 'reason', 'invalid_status');
  end if;

  update public.dkd_social_reports dkd_report_row
  set dkd_status_key = dkd_clean_status_key,
      dkd_admin_note_text = nullif(trim(coalesce(dkd_param_admin_note_text, dkd_report_row.dkd_admin_note_text, '')), ''),
      dkd_admin_user_id = dkd_current_admin_user_id,
      dkd_updated_at = now(),
      dkd_resolved_at = case when dkd_clean_status_key in ('dkd_resolved', 'dkd_dismissed') then now() else null end
  where dkd_report_row.dkd_id = dkd_param_report_id;

  get diagnostics dkd_updated_count = row_count;

  return jsonb_build_object('ok', dkd_updated_count > 0, 'reason', case when dkd_updated_count > 0 then 'updated' else 'not_found' end);
end;
$$;

revoke all on function public.dkd_social_admin_update_report_status(bigint, text, text) from public;
grant execute on function public.dkd_social_admin_update_report_status(bigint, text, text) to authenticated, service_role;

-- DKD Google Play policy center URL refresh for public HTML pages.
do $$
begin
  if to_regclass('public.dkd_policy_center_config') is not null then
    insert into public.dkd_policy_center_config (
      dkd_id_value,
      dkd_privacy_policy_doc_url_value,
      dkd_account_deletion_form_url_value,
      dkd_package_name_value,
      dkd_version_name_value,
      dkd_version_code_value,
      dkd_updated_at_value
    ) values (
      1,
      'https://www.draborneagle.com/draborngo/privacy/',
      'https://www.draborneagle.com/draborngo/account-deletion/',
      'com.draborneagle.draborngo',
      '0.212.0',
      212,
      now()
    )
    on conflict (dkd_id_value) do update set
      dkd_privacy_policy_doc_url_value = excluded.dkd_privacy_policy_doc_url_value,
      dkd_account_deletion_form_url_value = excluded.dkd_account_deletion_form_url_value,
      dkd_package_name_value = excluded.dkd_package_name_value,
      dkd_version_name_value = excluded.dkd_version_name_value,
      dkd_version_code_value = excluded.dkd_version_code_value,
      dkd_updated_at_value = excluded.dkd_updated_at_value;
  end if;
end $$;
