-- DKD DraBornGo v0.0.2 - Gönderi Paneli cüzdan ödeme RLS düzeltmesi
-- Önce: dkd_cargo_shipment_create RPC veya arka plandaki insert akışı RLS yüzünden
--        "new row violates row-level security policy" hatası verebilir.
-- Sonra: müşteri cüzdanından TL düşülür, gönderi kaydı oluşturulur,
--        kurye havuzuna cargo job düşer ve kullanıcı kendi gönderilerini okuyabilir.

alter table if exists public.dkd_profiles
  add column if not exists wallet_tl numeric(12,2) not null default 0;

create table if not exists public.dkd_cargo_shipments (
  id bigint generated by default as identity primary key,
  customer_user_id uuid references auth.users(id) on delete cascade,
  customer_first_name text,
  customer_last_name text,
  customer_national_id text,
  customer_phone_text text,
  pickup_address_text text,
  delivery_address_text text,
  delivery_note text,
  pickup_lat numeric,
  pickup_lng numeric,
  dropoff_lat numeric,
  dropoff_lng numeric,
  pickup_distance_km numeric(12,2) not null default 0,
  delivery_distance_km numeric(12,2) not null default 0,
  courier_fee_tl numeric(12,2) not null default 0,
  customer_charge_tl numeric(12,2) not null default 0,
  payment_status text not null default 'paid',
  paid_at timestamptz,
  package_content_text text,
  package_image_url text,
  pickup_proof_image_url text,
  package_weight_kg numeric(12,2) not null default 1,
  status text not null default 'open',
  courier_job_id bigint,
  assigned_courier_user_id uuid references auth.users(id) on delete set null,
  assigned_courier_plate_no text,
  assigned_courier_vehicle_type text,
  courier_eta_min integer,
  accepted_at timestamptz,
  picked_up_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.dkd_cargo_shipments add column if not exists customer_user_id uuid references auth.users(id) on delete cascade;
alter table public.dkd_cargo_shipments add column if not exists customer_first_name text;
alter table public.dkd_cargo_shipments add column if not exists customer_last_name text;
alter table public.dkd_cargo_shipments add column if not exists customer_national_id text;
alter table public.dkd_cargo_shipments add column if not exists customer_phone_text text;
alter table public.dkd_cargo_shipments add column if not exists pickup_address_text text;
alter table public.dkd_cargo_shipments add column if not exists delivery_address_text text;
alter table public.dkd_cargo_shipments add column if not exists delivery_note text;
alter table public.dkd_cargo_shipments add column if not exists pickup_lat numeric;
alter table public.dkd_cargo_shipments add column if not exists pickup_lng numeric;
alter table public.dkd_cargo_shipments add column if not exists dropoff_lat numeric;
alter table public.dkd_cargo_shipments add column if not exists dropoff_lng numeric;
alter table public.dkd_cargo_shipments add column if not exists pickup_distance_km numeric(12,2) not null default 0;
alter table public.dkd_cargo_shipments add column if not exists delivery_distance_km numeric(12,2) not null default 0;
alter table public.dkd_cargo_shipments add column if not exists courier_fee_tl numeric(12,2) not null default 0;
alter table public.dkd_cargo_shipments add column if not exists customer_charge_tl numeric(12,2) not null default 0;
alter table public.dkd_cargo_shipments add column if not exists payment_status text not null default 'paid';
alter table public.dkd_cargo_shipments add column if not exists paid_at timestamptz;
alter table public.dkd_cargo_shipments add column if not exists package_content_text text;
alter table public.dkd_cargo_shipments add column if not exists package_image_url text;
alter table public.dkd_cargo_shipments add column if not exists pickup_proof_image_url text;
alter table public.dkd_cargo_shipments add column if not exists package_weight_kg numeric(12,2) not null default 1;
alter table public.dkd_cargo_shipments add column if not exists status text not null default 'open';
alter table public.dkd_cargo_shipments add column if not exists courier_job_id bigint;
alter table public.dkd_cargo_shipments add column if not exists assigned_courier_user_id uuid references auth.users(id) on delete set null;
alter table public.dkd_cargo_shipments add column if not exists assigned_courier_plate_no text;
alter table public.dkd_cargo_shipments add column if not exists assigned_courier_vehicle_type text;
alter table public.dkd_cargo_shipments add column if not exists courier_eta_min integer;
alter table public.dkd_cargo_shipments add column if not exists accepted_at timestamptz;
alter table public.dkd_cargo_shipments add column if not exists picked_up_at timestamptz;
alter table public.dkd_cargo_shipments add column if not exists completed_at timestamptz;
alter table public.dkd_cargo_shipments add column if not exists created_at timestamptz not null default now();
alter table public.dkd_cargo_shipments add column if not exists updated_at timestamptz not null default now();

alter table if exists public.dkd_courier_jobs add column if not exists customer_user_id uuid references auth.users(id) on delete set null;
alter table if exists public.dkd_courier_jobs add column if not exists delivery_address_text text;
alter table if exists public.dkd_courier_jobs add column if not exists delivery_note text;
alter table if exists public.dkd_courier_jobs add column if not exists fee_tl numeric(12,2) not null default 0;
alter table if exists public.dkd_courier_jobs add column if not exists customer_charge_tl numeric(12,2) not null default 0;
alter table if exists public.dkd_courier_jobs add column if not exists cargo_meta jsonb not null default '{}'::jsonb;
alter table if exists public.dkd_courier_jobs add column if not exists cargo_shipment_id bigint;
alter table if exists public.dkd_courier_jobs add column if not exists pickup_status text not null default 'pending';
alter table if exists public.dkd_courier_jobs add column if not exists pickup_lat numeric;
alter table if exists public.dkd_courier_jobs add column if not exists pickup_lng numeric;
alter table if exists public.dkd_courier_jobs add column if not exists dropoff_lat numeric;
alter table if exists public.dkd_courier_jobs add column if not exists dropoff_lng numeric;
alter table if exists public.dkd_courier_jobs add column if not exists merchant_name text;
alter table if exists public.dkd_courier_jobs add column if not exists product_title text;

create index if not exists dkd_cargo_shipments_customer_created_idx
  on public.dkd_cargo_shipments(customer_user_id, created_at desc);

create index if not exists dkd_cargo_shipments_courier_status_idx
  on public.dkd_cargo_shipments(assigned_courier_user_id, status, created_at desc);

create index if not exists dkd_courier_jobs_cargo_shipment_idx
  on public.dkd_courier_jobs(cargo_shipment_id);

alter table public.dkd_cargo_shipments enable row level security;

drop policy if exists dkd_cargo_shipments_select_own_or_assigned on public.dkd_cargo_shipments;
create policy dkd_cargo_shipments_select_own_or_assigned
on public.dkd_cargo_shipments
for select
to authenticated
using (
  auth.uid() = customer_user_id
  or auth.uid() = assigned_courier_user_id
);

drop policy if exists dkd_cargo_shipments_insert_own on public.dkd_cargo_shipments;
create policy dkd_cargo_shipments_insert_own
on public.dkd_cargo_shipments
for insert
to authenticated
with check (auth.uid() = customer_user_id);

drop policy if exists dkd_cargo_shipments_update_own_or_assigned on public.dkd_cargo_shipments;
create policy dkd_cargo_shipments_update_own_or_assigned
on public.dkd_cargo_shipments
for update
to authenticated
using (
  auth.uid() = customer_user_id
  or auth.uid() = assigned_courier_user_id
)
with check (
  auth.uid() = customer_user_id
  or auth.uid() = assigned_courier_user_id
);

grant select, insert, update on public.dkd_cargo_shipments to authenticated;
grant select on public.dkd_cargo_shipments to anon;

-- Eski imza varsa dönüş tipi çakışmasın diye düşürülür.
drop function if exists public.dkd_cargo_shipment_create(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric
);

create or replace function public.dkd_cargo_shipment_create(
  dkd_param_customer_first_name text,
  dkd_param_customer_last_name text,
  dkd_param_customer_national_id text,
  dkd_param_customer_phone_text text,
  dkd_param_pickup_address_text text,
  dkd_param_delivery_address_text text,
  dkd_param_delivery_note_text text,
  dkd_param_package_content_text text,
  dkd_param_package_image_url text,
  dkd_param_package_weight_kg numeric,
  dkd_param_pickup_lat numeric,
  dkd_param_pickup_lng numeric,
  dkd_param_dropoff_lat numeric,
  dkd_param_dropoff_lng numeric,
  dkd_param_pickup_distance_km numeric,
  dkd_param_delivery_distance_km numeric,
  dkd_param_courier_fee_tl numeric,
  dkd_param_customer_charge_tl numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_wallet_before_tl_value numeric(12,2) := 0;
  dkd_wallet_after_tl_value numeric(12,2) := 0;
  dkd_shipment_id_value bigint := null;
  dkd_courier_job_id_value bigint := null;
  dkd_distance_km_value numeric(12,2) := 0;
  dkd_eta_min_value integer := 15;
  dkd_customer_name_value text := '';
  dkd_package_title_value text := '';
  dkd_cargo_meta_value jsonb := '{}'::jsonb;
begin
  if dkd_user_id_value is null then
    raise exception 'dkd_auth_required';
  end if;

  if coalesce(dkd_param_customer_charge_tl, 0) <= 0 then
    raise exception 'dkd_cargo_payment_amount_required';
  end if;

  insert into public.dkd_profiles (user_id)
  values (dkd_user_id_value)
  on conflict (user_id) do nothing;

  select round(coalesce(dkd_profile_scope.wallet_tl, 0)::numeric, 2)
  into dkd_wallet_before_tl_value
  from public.dkd_profiles dkd_profile_scope
  where dkd_profile_scope.user_id = dkd_user_id_value
  for update;

  if coalesce(dkd_wallet_before_tl_value, 0) < round(coalesce(dkd_param_customer_charge_tl, 0)::numeric, 2) then
    raise exception 'wallet_insufficient';
  end if;

  update public.dkd_profiles
  set wallet_tl = round(greatest(coalesce(wallet_tl, 0) - coalesce(dkd_param_customer_charge_tl, 0), 0)::numeric, 2)
  where user_id = dkd_user_id_value
  returning round(coalesce(wallet_tl, 0)::numeric, 2)
  into dkd_wallet_after_tl_value;

  dkd_distance_km_value := round(greatest(coalesce(dkd_param_pickup_distance_km, 0), 0) + greatest(coalesce(dkd_param_delivery_distance_km, 0), 0), 2);
  dkd_eta_min_value := greatest(12, least(180, (ceil(greatest(coalesce(dkd_distance_km_value, 1), 1) * 6) + 8)::integer));
  dkd_customer_name_value := trim(concat_ws(' ', nullif(trim(coalesce(dkd_param_customer_first_name, '')), ''), nullif(trim(coalesce(dkd_param_customer_last_name, '')), '')));
  dkd_package_title_value := coalesce(nullif(trim(coalesce(dkd_param_package_content_text, '')), ''), 'Paket');

  insert into public.dkd_cargo_shipments (
    customer_user_id,
    customer_first_name,
    customer_last_name,
    customer_national_id,
    customer_phone_text,
    pickup_address_text,
    delivery_address_text,
    delivery_note,
    pickup_lat,
    pickup_lng,
    dropoff_lat,
    dropoff_lng,
    pickup_distance_km,
    delivery_distance_km,
    courier_fee_tl,
    customer_charge_tl,
    payment_status,
    paid_at,
    package_content_text,
    package_image_url,
    package_weight_kg,
    status
  ) values (
    dkd_user_id_value,
    nullif(trim(coalesce(dkd_param_customer_first_name, '')), ''),
    nullif(trim(coalesce(dkd_param_customer_last_name, '')), ''),
    nullif(regexp_replace(coalesce(dkd_param_customer_national_id, ''), '[^0-9]', '', 'g'), ''),
    nullif(trim(coalesce(dkd_param_customer_phone_text, '')), ''),
    nullif(trim(coalesce(dkd_param_pickup_address_text, '')), ''),
    nullif(trim(coalesce(dkd_param_delivery_address_text, '')), ''),
    coalesce(nullif(trim(coalesce(dkd_param_delivery_note_text, '')), ''), 'Teşekkür Ederim'),
    dkd_param_pickup_lat,
    dkd_param_pickup_lng,
    dkd_param_dropoff_lat,
    dkd_param_dropoff_lng,
    round(greatest(coalesce(dkd_param_pickup_distance_km, 0), 0)::numeric, 2),
    round(greatest(coalesce(dkd_param_delivery_distance_km, 0), 0)::numeric, 2),
    round(greatest(coalesce(dkd_param_courier_fee_tl, 0), 0)::numeric, 2),
    round(greatest(coalesce(dkd_param_customer_charge_tl, 0), 0)::numeric, 2),
    'paid',
    now(),
    dkd_package_title_value,
    nullif(trim(coalesce(dkd_param_package_image_url, '')), ''),
    round(greatest(coalesce(dkd_param_package_weight_kg, 1), 0.1)::numeric, 2),
    'open'
  )
  returning id into dkd_shipment_id_value;

  dkd_cargo_meta_value := jsonb_build_object(
    'dkd_source', 'dkd_cargo_sender_panel_wallet_payment',
    'dkd_cargo_shipment_id', dkd_shipment_id_value,
    'dkd_customer_user_id', dkd_user_id_value,
    'dkd_customer_name', dkd_customer_name_value,
    'dkd_phone_text', dkd_param_customer_phone_text,
    'dkd_package_content_text', dkd_package_title_value,
    'dkd_package_image_url', dkd_param_package_image_url,
    'dkd_package_weight_kg', dkd_param_package_weight_kg,
    'dkd_pickup_address_text', dkd_param_pickup_address_text,
    'dkd_delivery_address_text', dkd_param_delivery_address_text,
    'dkd_delivery_note_text', coalesce(nullif(trim(coalesce(dkd_param_delivery_note_text, '')), ''), 'Teşekkür Ederim'),
    'dkd_customer_charge_tl', round(greatest(coalesce(dkd_param_customer_charge_tl, 0), 0)::numeric, 2),
    'dkd_wallet_before_tl', dkd_wallet_before_tl_value,
    'dkd_wallet_after_tl', dkd_wallet_after_tl_value
  );

  insert into public.dkd_courier_jobs (
    title,
    pickup,
    dropoff,
    reward_score,
    distance_km,
    eta_min,
    job_type,
    is_active,
    status,
    assigned_user_id,
    customer_user_id,
    delivery_address_text,
    delivery_note,
    fee_tl,
    customer_charge_tl,
    cargo_meta,
    cargo_shipment_id,
    pickup_status,
    pickup_lat,
    pickup_lng,
    dropoff_lat,
    dropoff_lng,
    merchant_name,
    product_title
  ) values (
    case when lower(dkd_package_title_value) like '%sipariş%' then dkd_package_title_value else dkd_package_title_value || ' Siparişi' end,
    coalesce(nullif(trim(coalesce(dkd_param_pickup_address_text, '')), ''), 'Gönderici adresi'),
    coalesce(nullif(trim(coalesce(dkd_param_delivery_address_text, '')), ''), 'Teslimat adresi'),
    16,
    greatest(coalesce(dkd_distance_km_value, 1), 1),
    dkd_eta_min_value,
    'cargo',
    true,
    'open',
    null,
    dkd_user_id_value,
    nullif(trim(coalesce(dkd_param_delivery_address_text, '')), ''),
    coalesce(nullif(trim(coalesce(dkd_param_delivery_note_text, '')), ''), 'Teşekkür Ederim'),
    round(greatest(coalesce(dkd_param_courier_fee_tl, 0), 0)::numeric, 2),
    round(greatest(coalesce(dkd_param_customer_charge_tl, 0), 0)::numeric, 2),
    dkd_cargo_meta_value,
    dkd_shipment_id_value,
    'pending',
    dkd_param_pickup_lat,
    dkd_param_pickup_lng,
    dkd_param_dropoff_lat,
    dkd_param_dropoff_lng,
    'Gönderi Paneli',
    dkd_package_title_value
  ) returning id into dkd_courier_job_id_value;

  update public.dkd_cargo_shipments
  set courier_job_id = dkd_courier_job_id_value,
      updated_at = now()
  where id = dkd_shipment_id_value;

  return jsonb_build_object(
    'ok', true,
    'dkd_ok_value', true,
    'id', dkd_shipment_id_value,
    'cargo_shipment_id', dkd_shipment_id_value,
    'dkd_cargo_shipment_id', dkd_shipment_id_value,
    'courier_job_id', dkd_courier_job_id_value,
    'dkd_courier_job_id', dkd_courier_job_id_value,
    'wallet_tl', dkd_wallet_after_tl_value,
    'dkd_wallet_before_tl', dkd_wallet_before_tl_value,
    'dkd_wallet_after_tl', dkd_wallet_after_tl_value,
    'payment_status', 'paid',
    'status', 'open'
  );
end;
$$;

revoke all on function public.dkd_cargo_shipment_create(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric
) from public;

grant execute on function public.dkd_cargo_shipment_create(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric,
  numeric
) to authenticated;

drop function if exists public.dkd_cargo_shipments_for_me();

create or replace function public.dkd_cargo_shipments_for_me()
returns table (
  id bigint,
  customer_user_id uuid,
  customer_first_name text,
  customer_last_name text,
  customer_full_name text,
  customer_national_id text,
  customer_phone_text text,
  pickup_address_text text,
  delivery_address_text text,
  delivery_note text,
  pickup_lat numeric,
  pickup_lng numeric,
  dropoff_lat numeric,
  dropoff_lng numeric,
  courier_fee_tl numeric,
  customer_charge_tl numeric,
  payment_status text,
  paid_at timestamptz,
  package_content_text text,
  package_image_url text,
  pickup_proof_image_url text,
  package_weight_kg numeric,
  status text,
  created_at timestamptz,
  accepted_at timestamptz,
  picked_up_at timestamptz,
  completed_at timestamptz,
  courier_job_id bigint,
  assigned_courier_user_id uuid,
  courier_display_name text,
  courier_plate_no text,
  courier_vehicle_type text,
  courier_lat numeric,
  courier_lng numeric,
  courier_eta_min integer,
  courier_heading_deg numeric,
  courier_location_updated_at timestamptz
)
language sql
security definer
set search_path = public, auth
as $$
  select
    dkd_shipment_scope.id,
    dkd_shipment_scope.customer_user_id,
    coalesce(dkd_shipment_scope.customer_first_name, '') as customer_first_name,
    coalesce(dkd_shipment_scope.customer_last_name, '') as customer_last_name,
    trim(concat_ws(' ', dkd_shipment_scope.customer_first_name, dkd_shipment_scope.customer_last_name)) as customer_full_name,
    coalesce(dkd_shipment_scope.customer_national_id, '') as customer_national_id,
    coalesce(dkd_shipment_scope.customer_phone_text, '') as customer_phone_text,
    coalesce(dkd_shipment_scope.pickup_address_text, '') as pickup_address_text,
    coalesce(dkd_shipment_scope.delivery_address_text, '') as delivery_address_text,
    coalesce(dkd_shipment_scope.delivery_note, '') as delivery_note,
    dkd_shipment_scope.pickup_lat,
    dkd_shipment_scope.pickup_lng,
    dkd_shipment_scope.dropoff_lat,
    dkd_shipment_scope.dropoff_lng,
    coalesce(dkd_shipment_scope.courier_fee_tl, 0)::numeric as courier_fee_tl,
    coalesce(dkd_shipment_scope.customer_charge_tl, 0)::numeric as customer_charge_tl,
    coalesce(dkd_shipment_scope.payment_status, '') as payment_status,
    dkd_shipment_scope.paid_at,
    coalesce(dkd_shipment_scope.package_content_text, '') as package_content_text,
    coalesce(dkd_shipment_scope.package_image_url, '') as package_image_url,
    coalesce(dkd_shipment_scope.pickup_proof_image_url, '') as pickup_proof_image_url,
    coalesce(dkd_shipment_scope.package_weight_kg, 0)::numeric as package_weight_kg,
    coalesce(dkd_shipment_scope.status, 'open') as status,
    dkd_shipment_scope.created_at,
    dkd_shipment_scope.accepted_at,
    dkd_shipment_scope.picked_up_at,
    dkd_shipment_scope.completed_at,
    dkd_shipment_scope.courier_job_id,
    dkd_shipment_scope.assigned_courier_user_id,
    coalesce(dkd_profile_scope.nickname, 'Kurye atandı') as courier_display_name,
    coalesce(dkd_live_scope.plate_no, dkd_shipment_scope.assigned_courier_plate_no, '') as courier_plate_no,
    coalesce(dkd_live_scope.vehicle_type, dkd_shipment_scope.assigned_courier_vehicle_type, dkd_profile_scope.courier_vehicle_type, '') as courier_vehicle_type,
    dkd_live_scope.lat as courier_lat,
    dkd_live_scope.lng as courier_lng,
    coalesce(dkd_live_scope.eta_min, dkd_shipment_scope.courier_eta_min) as courier_eta_min,
    dkd_live_scope.heading_deg as courier_heading_deg,
    dkd_live_scope.updated_at as courier_location_updated_at
  from public.dkd_cargo_shipments dkd_shipment_scope
  left join public.dkd_profiles dkd_profile_scope
    on dkd_profile_scope.user_id = dkd_shipment_scope.assigned_courier_user_id
  left join public.dkd_courier_live_locations dkd_live_scope
    on dkd_live_scope.courier_user_id = dkd_shipment_scope.assigned_courier_user_id
  where dkd_shipment_scope.customer_user_id = auth.uid()
     or dkd_shipment_scope.assigned_courier_user_id = auth.uid()
  order by dkd_shipment_scope.created_at desc nulls last, dkd_shipment_scope.id desc
  limit 50;
$$;

revoke all on function public.dkd_cargo_shipments_for_me() from public;
grant execute on function public.dkd_cargo_shipments_for_me() to authenticated;
