-- DKD DraBornGo v0.0.3 customer status push final reliability fix
-- Purpose: allow the app to read its own courier status push audit rows for local foreground fallback,
-- and keep remote push ticket diagnostics visible when Expo accepts HTTP but rejects an individual ticket.

begin;

create table if not exists public.dkd_courier_status_push_audit (
  id bigint generated by default as identity primary key,
  dkd_dedupe_key text not null,
  dkd_event_key text not null,
  dkd_job_id bigint,
  dkd_target_user_id uuid,
  expo_push_token text,
  dkd_title text,
  dkd_body text,
  dkd_payload jsonb not null default '{}'::jsonb,
  dkd_send_status text not null default 'pending',
  dkd_send_error text,
  dkd_created_at timestamptz not null default timezone('utc', now()),
  dkd_sent_at timestamptz
);

create unique index if not exists dkd_courier_status_push_audit_dedupe_idx
  on public.dkd_courier_status_push_audit(dkd_dedupe_key);
create index if not exists dkd_courier_status_push_audit_target_created_idx
  on public.dkd_courier_status_push_audit(dkd_target_user_id, dkd_created_at desc);
create index if not exists dkd_courier_status_push_audit_job_event_idx
  on public.dkd_courier_status_push_audit(dkd_job_id, dkd_event_key, dkd_created_at desc);

alter table public.dkd_courier_status_push_audit enable row level security;

drop policy if exists dkd_courier_status_push_audit_select_own_dkd on public.dkd_courier_status_push_audit;
create policy dkd_courier_status_push_audit_select_own_dkd
on public.dkd_courier_status_push_audit
for select
to authenticated
using (dkd_target_user_id = auth.uid());

grant select on table public.dkd_courier_status_push_audit to authenticated;
grant select, insert, update, delete on table public.dkd_courier_status_push_audit to service_role;

do $$
begin
  begin
    alter publication supabase_realtime add table public.dkd_courier_status_push_audit;
  exception
    when duplicate_object then null;
    when undefined_object then null;
    when others then null;
  end;
end $$;

-- Existing rows marked edge_sent were only HTTP/ticket-level attempts in older builds.
-- Keep them visible to the local foreground fallback instead of treating them as final delivery receipts.
update public.dkd_courier_status_push_audit
   set dkd_send_status = 'edge_ticket_ok'
 where dkd_send_status = 'edge_sent'
   and dkd_event_key in ('courier_job_accepted', 'courier_job_picked_up', 'courier_job_delivered', 'courier_job_status_changed')
   and dkd_created_at >= timezone('utc', now()) - interval '2 days';

notify pgrst, 'reload schema';

commit;
