import React, { useCallback, useEffect, useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { supabase } from '../lib/supabase';
import dkd_styles_value from './dkd_courier_styles';
import { dkd_palette_value } from './dkd_courier_theme';
import { dkd_badge_value, dkd_metric_value, dkd_modal_head_value, dkd_panel_title_value } from './dkd_courier_ui';
import { dkd_approve_account_deletion_request_value, dkd_fetch_admin_account_deletion_requests_value, dkd_reject_account_deletion_request_value } from '../services/dkd_account_deletion_service';
const dkd_e_value = React.createElement;

function dkd_admin_modal_value({ dkd_visible_value, dkd_on_close_value }) {
  const [dkd_counts_value, dkd_set_counts_value] = useState({ users: 0, jobs: 0, applications: 0 }); const [dkd_requests_value, dkd_set_requests_value] = useState([]);
  const dkd_load_value = useCallback(async () => { const [dkd_profiles_value, dkd_jobs_value, dkd_applications_value, dkd_delete_value] = await Promise.all([supabase.from('dkd_profiles').select('user_id', { count: 'exact', head: true }), supabase.from('dkd_courier_jobs').select('id', { count: 'exact', head: true }).is('dkd_deleted_at', null), supabase.from('dkd_courier_license_applications').select('id', { count: 'exact', head: true }).eq('status', 'pending'), dkd_fetch_admin_account_deletion_requests_value()]); dkd_set_counts_value({ users: dkd_profiles_value.count || 0, jobs: dkd_jobs_value.count || 0, applications: dkd_applications_value.count || 0 }); dkd_set_requests_value(Array.isArray(dkd_delete_value?.dkd_data_value) ? dkd_delete_value.dkd_data_value : []); }, []);
  useEffect(() => { if (dkd_visible_value) dkd_load_value(); }, [dkd_load_value, dkd_visible_value]);
  const dkd_decide_value = async (dkd_row_value, dkd_approve_value) => { const dkd_request_id_value = String(dkd_row_value?.dkd_id_value || ''); const dkd_result_value = dkd_approve_value ? await dkd_approve_account_deletion_request_value({ dkd_request_id_value, dkd_admin_note_value: 'v0.0.6 yönetim ekranından onaylandı.' }) : await dkd_reject_account_deletion_request_value({ dkd_request_id_value, dkd_admin_note_value: 'v0.0.6 yönetim ekranından reddedildi.' }); if (dkd_result_value?.dkd_error_value) return Alert.alert('Yönetim', String(dkd_result_value.dkd_error_value.message || dkd_result_value.dkd_error_value)); dkd_load_value(); };
  return dkd_e_value(Modal, { visible: Boolean(dkd_visible_value), animationType: 'slide', onRequestClose: dkd_on_close_value }, dkd_e_value(View, { style: dkd_styles_value.dkd_modal_root_value }, dkd_modal_head_value('Yönetim Operasyonları', 'Canlı sistem özeti', dkd_on_close_value, dkd_palette_value.dkd_gold_value, 'settings-outline'), dkd_e_value(ScrollView, { contentContainerStyle: dkd_styles_value.dkd_modal_content_value }, dkd_e_value(View, { style: dkd_styles_value.dkd_admin_metrics_value }, dkd_metric_value('people-outline', 'Kullanıcı', String(dkd_counts_value.users || 0), dkd_palette_value.dkd_cyan_value), dkd_metric_value('cube-outline', 'Teslimat', String(dkd_counts_value.jobs || 0), dkd_palette_value.dkd_green_value), dkd_metric_value('document-text-outline', 'Başvuru', String(dkd_counts_value.applications || 0), dkd_palette_value.dkd_orange_value)), dkd_e_value(Text, { style: dkd_styles_value.dkd_section_label_value }, 'HESAP SİLME TALEPLERİ'), dkd_requests_value.length ? dkd_requests_value.map((dkd_row_value) => dkd_e_value(View, { key: String(dkd_row_value.dkd_id_value), style: dkd_styles_value.dkd_simple_card_value }, dkd_panel_title_value('person-outline', String(dkd_row_value.dkd_display_name_value || dkd_row_value.dkd_user_email_value || 'Kullanıcı'), dkd_palette_value.dkd_gold_value), dkd_badge_value(String(dkd_row_value.dkd_status_value || 'pending').toUpperCase(), dkd_palette_value.dkd_gold_value), String(dkd_row_value.dkd_status_value || '') === 'pending' ? dkd_e_value(View, { style: dkd_styles_value.dkd_two_value }, dkd_e_value(Pressable, { onPress: () => dkd_decide_value(dkd_row_value, false), style: dkd_styles_value.dkd_danger_compact_value }, dkd_e_value(Text, { style: dkd_styles_value.dkd_danger_text_value }, 'REDDET')), dkd_e_value(Pressable, { onPress: () => dkd_decide_value(dkd_row_value, true), style: [dkd_styles_value.dkd_primary_compact_value, { backgroundColor: dkd_palette_value.dkd_green_value }] }, dkd_e_value(Text, { style: dkd_styles_value.dkd_primary_text_value }, 'ONAYLA VE SİL'))) : null)) : dkd_e_value(Text, { style: dkd_styles_value.dkd_empty_text_value }, 'Bekleyen talep yok.')))));
}
export { dkd_admin_modal_value };
