import { StyleSheet } from 'react-native';
import { dkd_palette_value } from './dkd_courier_theme';

const dkd_styles_value = StyleSheet.create({
  dkd_home_value: { flex: 1, backgroundColor: dkd_palette_value.dkd_bg_value },
  dkd_home_content_value: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 40, overflow: 'hidden' },
  dkd_ambient_orb_one_value: { position: 'absolute', width: 280, height: 280, borderRadius: 280, right: -170, top: 140, backgroundColor: '#145D862D' },
  dkd_ambient_orb_two_value: { position: 'absolute', width: 250, height: 250, borderRadius: 250, left: -165, top: 760, backgroundColor: '#742E8520' },
  dkd_disabled_value: { opacity: 0.45 },

  dkd_identity_pressable_value: { width: '100%' },
  dkd_identity_card_value: { width: '100%', minHeight: 118, borderRadius: 28, borderWidth: 1, borderColor: '#28465F', padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10, overflow: 'hidden' },
  dkd_identity_accent_value: { position: 'absolute', left: 0, top: 20, bottom: 20, width: 6, borderTopRightRadius: 7, borderBottomRightRadius: 7, backgroundColor: dkd_palette_value.dkd_cyan_value },
  dkd_identity_copy_value: { flex: 1, minWidth: 0 },
  dkd_brand_row_value: { flexDirection: 'row', alignItems: 'center', gap: 7, flexWrap: 'wrap' },
  dkd_brand_value: { color: dkd_palette_value.dkd_cyan_value, fontSize: 13, fontWeight: '900', letterSpacing: 0.8 },
  dkd_name_value: { color: '#FFFFFF', fontSize: 25, fontWeight: '900', marginTop: 5, letterSpacing: -0.6 },
  dkd_identity_status_row_value: { flexDirection: 'row', alignItems: 'center', marginTop: 3 },
  dkd_identity_meta_value: { flex: 1, color: '#9DB0C4', fontSize: 10, fontWeight: '800', letterSpacing: 0.35 },
  dkd_profile_icon_button_value: { width: 61, height: 66, borderRadius: 20, borderWidth: 1, borderColor: '#31506B', backgroundColor: '#0B1B2B', alignItems: 'center', justifyContent: 'center' },
  dkd_profile_icon_text_value: { color: '#DCEAF6', fontSize: 8, fontWeight: '900', marginTop: 4, letterSpacing: 0.7 },
  dkd_avatar_dot_value: { position: 'absolute', right: 1, bottom: 7, width: 14, height: 14, borderRadius: 20, borderWidth: 3, borderColor: '#081421' },
  dkd_badge_value: { minHeight: 25, paddingHorizontal: 9, borderRadius: 999, borderWidth: 1, alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-start' },
  dkd_badge_text_value: { fontSize: 9, fontWeight: '900', letterSpacing: 0.55 },

  dkd_command_shell_value: { width: '100%', marginTop: 14 },
  dkd_command_center_value: { borderRadius: 32, borderWidth: 1, borderColor: '#316180', padding: 18, overflow: 'hidden' },
  dkd_scan_line_value: { position: 'absolute', top: -30, bottom: -30, width: 70, transform: [{ rotate: '15deg' }] },
  dkd_command_top_value: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  dkd_command_live_row_value: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  dkd_command_eyebrow_value: { color: '#D8E5F2', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  dkd_command_content_value: { flexDirection: 'row', alignItems: 'center', marginTop: 14, gap: 8 },
  dkd_command_copy_value: { flex: 1, minWidth: 0 },
  dkd_command_title_value: { color: '#FFFFFF', fontSize: 27, lineHeight: 31, fontWeight: '900', letterSpacing: -0.8 },
  dkd_command_body_value: { color: '#AEC0D2', fontSize: 12, lineHeight: 18, fontWeight: '650', marginTop: 7 },
  dkd_motor_stage_value: { width: 128, height: 96, alignItems: 'center', justifyContent: 'center' },
  dkd_motor_aura_value: { position: 'absolute', width: 115, height: 115, borderRadius: 115 },
  dkd_route_strip_value: { height: 20, marginTop: 7, justifyContent: 'center', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 5 },
  dkd_route_line_value: { position: 'absolute', left: 7, right: 7, height: 2, backgroundColor: '#315069', zIndex: -1 },
  dkd_route_node_value: { width: 8, height: 8, borderRadius: 8, backgroundColor: '#42617A', borderWidth: 2, borderColor: '#0A1B2A' },
  dkd_online_button_value: { width: '100%', borderRadius: 21, overflow: 'hidden' },
  dkd_online_button_fill_value: { minHeight: 62, borderRadius: 21, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 17, gap: 10 },
  dkd_online_button_text_value: { flex: 1, textAlign: 'center', color: '#041019', fontSize: 14, fontWeight: '900', letterSpacing: 0.7 },

  dkd_metrics_row_value: { flexDirection: 'row', gap: 8, marginTop: 12 },
  dkd_metric_value: { flex: 1, minHeight: 92, borderRadius: 22, borderWidth: 1, backgroundColor: '#081521', padding: 10 },
  dkd_metric_icon_value: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 7 },
  dkd_metric_label_value: { color: '#8297AC', fontSize: 8, fontWeight: '900', letterSpacing: 0.75, textTransform: 'uppercase' },
  dkd_metric_number_value: { fontSize: 12, lineHeight: 16, fontWeight: '900', marginTop: 4 },

  dkd_section_header_value: { marginTop: 27, marginBottom: 12, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 },
  dkd_section_kicker_value: { color: dkd_palette_value.dkd_cyan_value, fontSize: 9, fontWeight: '900', letterSpacing: 1.15 },
  dkd_section_title_value: { color: '#FFFFFF', fontSize: 25, fontWeight: '900', marginTop: 4, letterSpacing: -0.6 },
  dkd_section_title_small_value: { color: '#FFFFFF', fontSize: 22, fontWeight: '900', marginTop: 4, letterSpacing: -0.5 },
  dkd_section_icon_shell_value: { width: 46, height: 46, borderRadius: 16, backgroundColor: '#241D0C', alignItems: 'center', justifyContent: 'center' },

  dkd_operation_card_pressable_value: { width: '100%', borderRadius: 28, overflow: 'hidden' },
  dkd_operation_card_value: { width: '100%', minHeight: 232, borderRadius: 28, borderWidth: 1, borderColor: '#2A5A77', padding: 17, overflow: 'hidden' },
  dkd_operation_card_top_value: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  dkd_operation_motor_value: { width: 108, height: 72, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: '#0A2232' },
  dkd_operation_title_value: { color: '#FFFFFF', fontSize: 22, fontWeight: '900', marginTop: 13, letterSpacing: -0.45 },
  dkd_operation_body_value: { color: '#9EB1C4', fontSize: 12, lineHeight: 18, fontWeight: '650', marginTop: 7, maxWidth: '92%' },
  dkd_operation_footer_value: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 17 },
  dkd_operation_open_value: { color: dkd_palette_value.dkd_cyan_value, fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  dkd_operation_edge_value: { position: 'absolute', left: 0, right: 0, top: 0, height: 5 },

  dkd_service_operation_value: { width: '100%', minHeight: 126, borderRadius: 26, borderWidth: 1, borderColor: '#29614C', padding: 15, flexDirection: 'row', alignItems: 'center', gap: 13 },
  dkd_service_operation_icon_value: { width: 58, height: 58, borderRadius: 20, backgroundColor: '#0B2A22', alignItems: 'center', justifyContent: 'center' },
  dkd_service_operation_kicker_value: { color: dkd_palette_value.dkd_green_value, fontSize: 9, fontWeight: '900', letterSpacing: 1.2 },
  dkd_service_operation_title_value: { color: '#FFFFFF', fontSize: 17, fontWeight: '900', marginTop: 3, letterSpacing: -0.25 },
  dkd_service_operation_body_value: { color: '#8FA9A0', fontSize: 10, lineHeight: 15, fontWeight: '650', marginTop: 5 },

  dkd_quick_grid_value: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  dkd_quick_tile_wrap_value: { flexBasis: '47.5%', flexGrow: 1, maxWidth: '48.5%', minWidth: 0 },
  dkd_quick_tile_value: { width: '100%', minHeight: 170, borderRadius: 25, overflow: 'hidden' },
  dkd_quick_tile_fill_value: { flex: 1, minHeight: 170, borderRadius: 25, borderWidth: 1, borderColor: '#253A50', padding: 14, overflow: 'hidden' },
  dkd_quick_tile_icon_value: { width: 45, height: 45, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  dkd_quick_tile_title_value: { color: '#FFFFFF', fontSize: 17, lineHeight: 21, fontWeight: '900', marginTop: 12, letterSpacing: -0.25 },
  dkd_quick_tile_subtitle_value: { flex: 1, color: '#8EA2B6', fontSize: 10, lineHeight: 15, fontWeight: '700', marginTop: 5 },
  dkd_quick_tile_footer_value: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 11 },
  dkd_quick_tile_open_value: { fontSize: 9, fontWeight: '900', letterSpacing: 1.1 },
  dkd_quick_tile_edge_value: { position: 'absolute', top: 0, left: 14, right: 14, height: 4, borderBottomLeftRadius: 4, borderBottomRightRadius: 4 },

  dkd_admin_card_pressable_value: { width: '100%', borderRadius: 25, overflow: 'hidden' },
  dkd_admin_card_value: { minHeight: 118, borderRadius: 25, borderWidth: 1, borderColor: '#66562D', padding: 15, flexDirection: 'row', alignItems: 'center', gap: 12 },
  dkd_admin_icon_value: { width: 54, height: 54, borderRadius: 18, backgroundColor: '#2A230E', alignItems: 'center', justifyContent: 'center' },
  dkd_admin_kicker_value: { color: dkd_palette_value.dkd_gold_value, fontSize: 9, fontWeight: '900', letterSpacing: 1.2 },
  dkd_admin_title_value: { color: '#FFFFFF', fontSize: 18, fontWeight: '900', marginTop: 2 },
  dkd_admin_body_value: { color: '#A59D82', fontSize: 10, lineHeight: 15, fontWeight: '650', marginTop: 4 },

  dkd_footer_value: { marginTop: 18, minHeight: 72, borderRadius: 22, borderWidth: 1, borderColor: '#20364C', backgroundColor: '#06111C', padding: 11, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  dkd_footer_brand_value: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  dkd_footer_title_value: { color: '#EAF4FF', fontSize: 12, fontWeight: '900' },
  dkd_footer_meta_value: { color: '#6F8298', fontSize: 8, fontWeight: '700', marginTop: 3 },
  dkd_logout_value: { minHeight: 43, paddingHorizontal: 12, borderRadius: 15, borderWidth: 1, borderColor: '#5A2D40', backgroundColor: '#28131D', flexDirection: 'row', alignItems: 'center', gap: 5 },
  dkd_logout_text_value: { color: '#FF9AAF', fontSize: 9, fontWeight: '900', letterSpacing: 0.7 },

  dkd_modal_root_value: { flex: 1, backgroundColor: dkd_palette_value.dkd_bg_value },
  dkd_modal_head_value: { paddingTop: 48, paddingHorizontal: 16, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: '#1B3146', flexDirection: 'row', alignItems: 'center', gap: 11 },
  dkd_modal_head_icon_value: { width: 46, height: 46, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  dkd_modal_title_value: { color: '#FFFFFF', fontSize: 20, fontWeight: '900', letterSpacing: -0.35 },
  dkd_modal_subtitle_value: { color: '#8297AC', fontSize: 9, fontWeight: '750', marginTop: 3 },
  dkd_modal_close_value: { width: 44, height: 44, borderRadius: 15, borderWidth: 1, borderColor: '#263E56', backgroundColor: '#0D1A29', alignItems: 'center', justifyContent: 'center' },
  dkd_modal_content_value: { padding: 16, paddingBottom: 46 },
  dkd_profile_hero_value: { minHeight: 190, borderRadius: 26, borderWidth: 1, borderColor: '#41366D', alignItems: 'center', justifyContent: 'center', padding: 18, marginBottom: 7 },
  dkd_profile_hero_name_value: { color: '#FFFFFF', fontSize: 22, fontWeight: '900', marginTop: 8 },
  dkd_profile_hero_meta_value: { color: '#95A7BB', fontSize: 10, fontWeight: '750', marginTop: 4 },
  dkd_form_label_value: { color: '#8195AB', fontSize: 9, fontWeight: '900', marginTop: 13, marginBottom: 6, letterSpacing: 1.1 },
  dkd_input_value: { minHeight: 53, borderRadius: 16, borderWidth: 1, borderColor: '#263D54', backgroundColor: '#091522', color: '#FFFFFF', paddingHorizontal: 14, marginBottom: 9, fontWeight: '750' },
  dkd_primary_value: { minHeight: 54, borderRadius: 17, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 13, marginTop: 10 },
  dkd_primary_text_value: { color: '#041019', fontWeight: '900', textAlign: 'center', letterSpacing: 0.4 },
  dkd_outline_value: { minHeight: 50, borderRadius: 16, borderWidth: 1, borderColor: '#2B526C', backgroundColor: '#091D2B', alignItems: 'center', justifyContent: 'center', marginTop: 10, paddingHorizontal: 12 },
  dkd_outline_text_value: { color: dkd_palette_value.dkd_cyan_value, fontWeight: '900', fontSize: 10, textAlign: 'center', letterSpacing: 0.5 },
  dkd_notice_value: { marginTop: 14, padding: 14, borderRadius: 18, backgroundColor: '#21151E', borderWidth: 1, borderColor: '#543044' },
  dkd_notice_title_value: { color: '#FFB4C5', fontWeight: '900' },
  dkd_danger_value: { minHeight: 54, borderRadius: 17, borderWidth: 1, borderColor: '#6A3044', backgroundColor: '#35151F', alignItems: 'center', justifyContent: 'center', marginTop: 14, paddingHorizontal: 12 },
  dkd_danger_text_value: { color: '#FFB3C3', fontWeight: '900', fontSize: 10, textAlign: 'center' },
  dkd_courier_control_value: { borderRadius: 28, borderWidth: 1, borderColor: '#2B536C', padding: 16, overflow: 'hidden' },
  dkd_courier_control_top_value: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  dkd_courier_control_eyebrow_value: { flex: 1, color: '#D7E4F0', fontSize: 10, fontWeight: '900', letterSpacing: 1.0 },
  dkd_courier_visual_row_value: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  dkd_courier_control_title_value: { color: '#FFFFFF', fontSize: 24, fontWeight: '900' },
  dkd_section_label_value: { color: '#E8F1FB', fontSize: 11, fontWeight: '900', letterSpacing: 1.0, marginTop: 24, marginBottom: 10 },
  dkd_empty_value: { minHeight: 170, borderRadius: 24, borderWidth: 1, borderStyle: 'dashed', borderColor: '#2A435B', backgroundColor: '#07131F', alignItems: 'center', justifyContent: 'center', padding: 20 },
  dkd_empty_title_value: { color: '#FFFFFF', fontSize: 16, fontWeight: '900', marginTop: 9 },
  dkd_empty_body_value: { color: '#8296AB', fontSize: 10, fontWeight: '650', marginTop: 5, textAlign: 'center' },
  dkd_empty_text_value: { color: '#8397AC', textAlign: 'center', fontWeight: '700', paddingVertical: 22 },
  dkd_job_card_value: { padding: 15, borderRadius: 21, borderWidth: 1, borderColor: '#223E58', marginBottom: 9 },
  dkd_panel_title_row_value: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  dkd_panel_icon_value: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  dkd_panel_title_value: { flex: 1, color: '#FFFFFF', fontSize: 15, fontWeight: '900' },
  dkd_panel_body_value: { color: '#9DAFC1', fontSize: 11, lineHeight: 18, fontWeight: '650', marginTop: 7 },
  dkd_meta_value: { color: '#7D92A8', fontSize: 9, fontWeight: '800', marginTop: 9 },
  dkd_service_hero_value: { borderRadius: 25, borderWidth: 1, borderColor: '#275C49', padding: 16 },
  dkd_simple_card_value: { padding: 15, borderRadius: 20, borderWidth: 1, borderColor: '#263B51', backgroundColor: '#091522', marginBottom: 9 },
  dkd_list_row_value: { width: '100%', minHeight: 78, borderRadius: 20, borderWidth: 1, borderColor: '#223C54', backgroundColor: '#091522', marginBottom: 9, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 11 },
  dkd_list_row_icon_value: { width: 45, height: 45, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  dkd_list_row_title_value: { color: '#FFFFFF', fontSize: 15, fontWeight: '900' },
  dkd_list_row_meta_value: { color: '#899DB2', fontSize: 10, fontWeight: '700', marginTop: 4 },
  dkd_form_card_value: { borderRadius: 25, borderWidth: 1, borderColor: '#65452B', padding: 16 },
  dkd_support_hero_value: { borderRadius: 25, borderWidth: 1, borderColor: '#2C4F7D', alignItems: 'center', padding: 20, marginBottom: 12 },
  dkd_support_title_value: { color: '#FFFFFF', fontSize: 20, fontWeight: '900', marginTop: 9 },
  dkd_support_body_value: { color: '#91A5BB', fontSize: 11, lineHeight: 18, fontWeight: '650', textAlign: 'center', marginTop: 5 },
  dkd_admin_metrics_value: { flexDirection: 'row', gap: 8 },
  dkd_two_value: { flexDirection: 'row', gap: 8, marginTop: 12 },
  dkd_danger_compact_value: { flex: 1, minHeight: 46, borderRadius: 14, backgroundColor: '#32151F', alignItems: 'center', justifyContent: 'center' },
  dkd_primary_compact_value: { flex: 1.25, minHeight: 46, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
});

export default dkd_styles_value;
