import React, { useEffect, useRef } from 'react';
import { Animated, Easing, Image, Pressable, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import * as Haptics from 'expo-haptics';
import dkd_styles_value from './dkd_courier_styles';
import { dkd_color_alpha_value, dkd_palette_value } from './dkd_courier_theme';

const dkd_e_value = React.createElement;

function dkd_haptic_value(dkd_kind_value = 'light') {
  const dkd_style_value = dkd_kind_value === 'medium' ? Haptics.ImpactFeedbackStyle.Medium : Haptics.ImpactFeedbackStyle.Light;
  Haptics.impactAsync(dkd_style_value).catch(() => {});
}
function dkd_motion_pressable_value({ dkd_children_value, dkd_on_press_value, dkd_pressable_style_value, dkd_container_style_value, dkd_delay_value = 0, dkd_disabled_value = false, dkd_label_value, dkd_haptic_kind_value = 'light' }) {
  const dkd_scale_value = useRef(new Animated.Value(1)).current;
  const dkd_enter_value = useRef(new Animated.Value(0)).current;
  useEffect(() => { Animated.timing(dkd_enter_value, { toValue: 1, duration: 440, delay: Number(dkd_delay_value || 0), easing: Easing.out(Easing.cubic), useNativeDriver: true }).start(); }, [dkd_delay_value, dkd_enter_value]);
  const dkd_press_in_value = () => { if (!dkd_disabled_value) Animated.spring(dkd_scale_value, { toValue: 0.965, speed: 34, bounciness: 3, useNativeDriver: true }).start(); };
  const dkd_press_out_value = () => { if (!dkd_disabled_value) Animated.spring(dkd_scale_value, { toValue: 1, speed: 24, bounciness: 7, useNativeDriver: true }).start(); };
  const dkd_press_value = () => { if (!dkd_disabled_value) { dkd_haptic_value(dkd_haptic_kind_value); dkd_on_press_value?.(); } };
  return dkd_e_value(Animated.View, { style: [dkd_container_style_value, { opacity: dkd_enter_value, transform: [{ translateY: dkd_enter_value.interpolate({ inputRange: [0, 1], outputRange: [16, 0] }) }, { scale: dkd_scale_value }] }] }, dkd_e_value(Pressable, { disabled: dkd_disabled_value, accessibilityRole: 'button', accessibilityLabel: dkd_label_value, onPress: dkd_press_value, onPressIn: dkd_press_in_value, onPressOut: dkd_press_out_value, style: [dkd_pressable_style_value, dkd_disabled_value ? dkd_styles_value.dkd_disabled_value : null] }, dkd_children_value));
}
function dkd_pulse_value({ dkd_color_value = dkd_palette_value.dkd_green_value, dkd_size_value = 9 }) {
  const dkd_anim_value = useRef(new Animated.Value(0)).current;
  useEffect(() => { const dkd_loop_value = Animated.loop(Animated.sequence([Animated.timing(dkd_anim_value, { toValue: 1, duration: 850, easing: Easing.out(Easing.quad), useNativeDriver: true }), Animated.timing(dkd_anim_value, { toValue: 0, duration: 850, easing: Easing.in(Easing.quad), useNativeDriver: true })])); dkd_loop_value.start(); return () => dkd_loop_value.stop(); }, [dkd_anim_value]);
  return dkd_e_value(View, { style: { width: dkd_size_value + 14, height: dkd_size_value + 14, alignItems: 'center', justifyContent: 'center' } }, dkd_e_value(Animated.View, { style: { position: 'absolute', width: dkd_size_value + 14, height: dkd_size_value + 14, borderRadius: 30, backgroundColor: dkd_color_value, opacity: dkd_anim_value.interpolate({ inputRange: [0, 1], outputRange: [0.08, 0.28] }), transform: [{ scale: dkd_anim_value.interpolate({ inputRange: [0, 1], outputRange: [0.7, 1.08] }) }] } }), dkd_e_value(View, { style: { width: dkd_size_value, height: dkd_size_value, borderRadius: 20, backgroundColor: dkd_color_value } }));
}
function dkd_scan_line_value({ dkd_color_value }) {
  const dkd_scan_value = useRef(new Animated.Value(0)).current;
  useEffect(() => { const dkd_loop_value = Animated.loop(Animated.sequence([Animated.timing(dkd_scan_value, { toValue: 1, duration: 2500, easing: Easing.inOut(Easing.sin), useNativeDriver: true }), Animated.timing(dkd_scan_value, { toValue: 0, duration: 0, useNativeDriver: true }), Animated.delay(700)])); dkd_loop_value.start(); return () => dkd_loop_value.stop(); }, [dkd_scan_value]);
  return dkd_e_value(Animated.View, { pointerEvents: 'none', style: [dkd_styles_value.dkd_scan_line_value, { backgroundColor: dkd_color_value, opacity: dkd_scan_value.interpolate({ inputRange: [0, 0.5, 1], outputRange: [0, 0.34, 0] }), transform: [{ translateX: dkd_scan_value.interpolate({ inputRange: [0, 1], outputRange: [-170, 380] }) }] }] });
}
function dkd_profile_avatar_value({ dkd_uri_value, dkd_emoji_value, dkd_online_value, dkd_size_value = 72, dkd_on_error_value }) {
  const dkd_ring_value = useRef(new Animated.Value(0)).current; const dkd_color_value = dkd_online_value ? dkd_palette_value.dkd_green_value : dkd_palette_value.dkd_cyan_value;
  useEffect(() => { const dkd_loop_value = Animated.loop(Animated.sequence([Animated.timing(dkd_ring_value, { toValue: 1, duration: 1200, useNativeDriver: true }), Animated.timing(dkd_ring_value, { toValue: 0, duration: 1200, useNativeDriver: true })])); dkd_loop_value.start(); return () => dkd_loop_value.stop(); }, [dkd_ring_value]);
  return dkd_e_value(View, { style: { width: dkd_size_value + 14, height: dkd_size_value + 14, alignItems: 'center', justifyContent: 'center' } }, dkd_e_value(Animated.View, { style: { position: 'absolute', width: dkd_size_value + 12, height: dkd_size_value + 12, borderRadius: 999, borderWidth: 2, borderColor: dkd_color_value, opacity: dkd_ring_value.interpolate({ inputRange: [0, 1], outputRange: [0.35, 0.95] }), transform: [{ scale: dkd_ring_value.interpolate({ inputRange: [0, 1], outputRange: [0.98, 1.035] }) }] } }), dkd_uri_value ? dkd_e_value(Image, { source: { uri: dkd_uri_value }, onError: dkd_on_error_value, resizeMode: 'cover', style: { width: dkd_size_value, height: dkd_size_value, borderRadius: 999, backgroundColor: '#102033' } }) : dkd_e_value(View, { style: { width: dkd_size_value, height: dkd_size_value, borderRadius: 999, backgroundColor: '#102033', alignItems: 'center', justifyContent: 'center' } }, dkd_e_value(Text, { style: { fontSize: Math.round(dkd_size_value * 0.44) } }, String(dkd_emoji_value || '🦅'))), dkd_e_value(View, { style: [dkd_styles_value.dkd_avatar_dot_value, { backgroundColor: dkd_color_value }] }));
}
function dkd_badge_value(dkd_text_value, dkd_color_value) { return dkd_e_value(View, { style: [dkd_styles_value.dkd_badge_value, { borderColor: dkd_color_alpha_value(dkd_color_value, '66'), backgroundColor: dkd_color_alpha_value(dkd_color_value, '17') }] }, dkd_e_value(Text, { style: [dkd_styles_value.dkd_badge_text_value, { color: dkd_color_value }] }, dkd_text_value)); }
function dkd_metric_value(dkd_icon_value, dkd_label_value, dkd_value_value, dkd_color_value) { return dkd_e_value(View, { style: [dkd_styles_value.dkd_metric_value, { borderColor: dkd_color_alpha_value(dkd_color_value, '44') }] }, dkd_e_value(View, { style: [dkd_styles_value.dkd_metric_icon_value, { backgroundColor: dkd_color_alpha_value(dkd_color_value, '18') }] }, dkd_e_value(Ionicons, { name: dkd_icon_value, size: 18, color: dkd_color_value })), dkd_e_value(Text, { style: dkd_styles_value.dkd_metric_label_value }, dkd_label_value), dkd_e_value(Text, { style: [dkd_styles_value.dkd_metric_number_value, { color: dkd_color_value }], numberOfLines: 2 }, dkd_value_value)); }
function dkd_panel_title_value(dkd_icon_value, dkd_title_value, dkd_color_value) { return dkd_e_value(View, { style: dkd_styles_value.dkd_panel_title_row_value }, dkd_e_value(View, { style: [dkd_styles_value.dkd_panel_icon_value, { backgroundColor: dkd_color_alpha_value(dkd_color_value, '1C') }] }, dkd_e_value(Ionicons, { name: dkd_icon_value, size: 19, color: dkd_color_value })), dkd_e_value(Text, { style: dkd_styles_value.dkd_panel_title_value }, dkd_title_value)); }
function dkd_modal_head_value(dkd_title_value, dkd_subtitle_value, dkd_on_close_value, dkd_color_value, dkd_icon_value) { return dkd_e_value(LinearGradient, { colors: ['#091929', '#06111D', '#040A12'], start: { x: 0, y: 0 }, end: { x: 1, y: 1 }, style: dkd_styles_value.dkd_modal_head_value }, dkd_e_value(View, { style: [dkd_styles_value.dkd_modal_head_icon_value, { borderColor: dkd_color_alpha_value(dkd_color_value, '66'), backgroundColor: dkd_color_alpha_value(dkd_color_value, '17') }] }, dkd_e_value(Ionicons, { name: dkd_icon_value, size: 22, color: dkd_color_value })), dkd_e_value(View, { style: { flex: 1 } }, dkd_e_value(Text, { style: dkd_styles_value.dkd_modal_title_value }, dkd_title_value), dkd_e_value(Text, { style: dkd_styles_value.dkd_modal_subtitle_value }, dkd_subtitle_value)), dkd_e_value(Pressable, { onPress: dkd_on_close_value, style: dkd_styles_value.dkd_modal_close_value }, dkd_e_value(Ionicons, { name: 'close', size: 24, color: '#F6FAFF' }))); }

export { dkd_haptic_value, dkd_motion_pressable_value, dkd_pulse_value, dkd_scan_line_value, dkd_profile_avatar_value, dkd_badge_value, dkd_metric_value, dkd_panel_title_value, dkd_modal_head_value };
