create extension if not exists pgcrypto;

create table if not exists public.dkd_businesses (
  id uuid primary key default gen_random_uuid(),
  business_key text,
  slug text,
  name text not null,
  category text default 'general',
  city text,
  district text,
  address_text text,
  sponsor_name text,
  sponsor_enabled boolean not null default false,
  opens_at text,
  closes_at text,
  stock_alert_threshold integer not null default 10,
  is_active boolean not null default true,
  lat numeric,
  lng numeric,
  radius_m integer not null default 80,
  meta jsonb not null default '{}'::jsonb,
  timezone_name text default 'Europe/Istanbul',
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dkd_business_memberships (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.dkd_businesses(id) on delete cascade,
  user_id uuid not null,
  role_key text not null default 'staff',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, user_id)
);

create table if not exists public.dkd_business_access_codes (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.dkd_businesses(id) on delete cascade,
  label text,
  role_key text not null default 'manager',
  access_code text not null unique,
  is_active boolean not null default true,
  claimed_by uuid,
  claimed_at timestamptz,
  expires_at timestamptz,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dkd_business_memberships_user_idx on public.dkd_business_memberships(user_id, is_active);
create index if not exists dkd_business_access_codes_business_idx on public.dkd_business_access_codes(business_id, is_active);

create or replace function public.dkd_business_is_member(dkd_param_business_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.dkd_business_memberships dkd_alias_membership
    where dkd_alias_membership.business_id = dkd_param_business_id
      and dkd_alias_membership.user_id = auth.uid()
      and dkd_alias_membership.is_active = true
  );
$$;

create or replace function public.dkd_business_claim_access_code(dkd_param_access_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_code public.dkd_business_access_codes%rowtype;
  dkd_var_user_id uuid := auth.uid();
begin
  if dkd_var_user_id is null then
    return jsonb_build_object('ok', false, 'reason', 'auth_required');
  end if;

  select * into dkd_var_code
  from public.dkd_business_access_codes
  where access_code = upper(trim(coalesce(dkd_param_access_code, '')))
  limit 1;

  if dkd_var_code.id is null then
    return jsonb_build_object('ok', false, 'reason', 'code_not_found');
  end if;
  if dkd_var_code.is_active is not true then
    return jsonb_build_object('ok', false, 'reason', 'code_inactive');
  end if;
  if dkd_var_code.expires_at is not null and dkd_var_code.expires_at < now() then
    return jsonb_build_object('ok', false, 'reason', 'code_expired');
  end if;

  insert into public.dkd_business_memberships (business_id, user_id, role_key, is_active, created_at, updated_at)
  values (dkd_var_code.business_id, dkd_var_user_id, coalesce(nullif(trim(dkd_var_code.role_key), ''), 'manager'), true, now(), now())
  on conflict (business_id, user_id) do update
    set role_key = excluded.role_key, is_active = true, updated_at = now();

  update public.dkd_business_access_codes
  set is_active = false, claimed_by = dkd_var_user_id, claimed_at = now(), updated_at = now()
  where id = dkd_var_code.id;

  return jsonb_build_object('ok', true, 'business_id', dkd_var_code.business_id, 'role_key', dkd_var_code.role_key);
end;
$$;

create or replace function public.dkd_business_create_access_code(
  dkd_param_business_id uuid,
  dkd_param_role_key text default 'manager',
  dkd_param_label text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_var_code text;
begin
  if coalesce(public.dkd_is_admin(), false) is not true then
    raise exception 'admin_required';
  end if;
  dkd_var_code := 'DKD-' || substring(replace(gen_random_uuid()::text, '-', '') from 1 for 8);
  insert into public.dkd_business_access_codes (business_id, access_code, role_key, label, is_active)
  values (
    dkd_param_business_id,
    upper(dkd_var_code),
    coalesce(nullif(trim(coalesce(dkd_param_role_key, '')), ''), 'manager'),
    nullif(trim(coalesce(dkd_param_label, '')), ''),
    true
  );
  return upper(dkd_var_code);
end;
$$;

alter table public.dkd_businesses enable row level security;
alter table public.dkd_business_memberships enable row level security;
alter table public.dkd_business_access_codes enable row level security;

drop policy if exists dkd_businesses_read on public.dkd_businesses;
create policy dkd_businesses_read on public.dkd_businesses for select to authenticated using (true);

drop policy if exists dkd_business_memberships_self_read on public.dkd_business_memberships;
create policy dkd_business_memberships_self_read on public.dkd_business_memberships for select to authenticated using (user_id = auth.uid() or coalesce(public.dkd_is_admin(), false));

drop policy if exists dkd_business_access_codes_admin_read on public.dkd_business_access_codes;
create policy dkd_business_access_codes_admin_read on public.dkd_business_access_codes for select to authenticated using (coalesce(public.dkd_is_admin(), false));

grant select on public.dkd_businesses to authenticated;
grant select on public.dkd_business_memberships to authenticated;
grant select on public.dkd_business_access_codes to authenticated;
grant execute on function public.dkd_business_is_member(uuid) to authenticated;
grant execute on function public.dkd_business_claim_access_code(text) to authenticated;
grant execute on function public.dkd_business_create_access_code(uuid, text, text) to authenticated;
