-- DKD DraBornGo v0.0.3 customer status push edge-direct fix
-- Purpose: make courier accept / picked-up / delivered notifications reach the customer for restaurant and sender-panel orders.
-- Safe rerun: no customer/order/profile rows are deleted.

begin;

do $$
begin
  create extension if not exists pg_net;
exception
  when others then
    null;
end $$;

alter table if exists public.dkd_courier_jobs add column if not exists customer_user_id uuid;
alter table if exists public.dkd_courier_jobs add column if not exists pickup_status text not null default 'pending';
alter table if exists public.dkd_courier_jobs add column if not exists picked_up_at timestamptz;
alter table if exists public.dkd_courier_jobs add column if not exists cargo_meta jsonb not null default '{}'::jsonb;
alter table if exists public.dkd_courier_jobs add column if not exists cargo_shipment_id bigint;

create table if not exists public.dkd_courier_status_push_audit (
  dkd_audit_id bigint generated by default as identity primary key,
  dkd_dedupe_key text not null,
  dkd_event_key text not null,
  dkd_job_id bigint not null,
  dkd_target_user_id uuid null,
  expo_push_token text not null,
  dkd_title text not null,
  dkd_body text not null,
  dkd_payload jsonb not null default '{}'::jsonb,
  dkd_send_status text not null default 'pending',
  dkd_send_error text null,
  dkd_created_at timestamptz not null default timezone('utc', now()),
  dkd_sent_at timestamptz null
);

alter table public.dkd_courier_status_push_audit enable row level security;
create unique index if not exists dkd_courier_status_push_audit_dedupe_idx
  on public.dkd_courier_status_push_audit(dkd_dedupe_key);
create index if not exists dkd_courier_status_push_audit_job_event_idx
  on public.dkd_courier_status_push_audit(dkd_job_id, dkd_event_key, dkd_created_at desc);
grant select, insert, update, delete on table public.dkd_courier_status_push_audit to service_role;
grant select on table public.dkd_courier_status_push_audit to authenticated;

drop function if exists public.dkd_json_user_id_text_dkd(jsonb);
create function public.dkd_json_user_id_text_dkd(dkd_param_json_value jsonb)
returns text
language sql
immutable
as $$
  select coalesce(
    nullif(dkd_param_json_value->>'dkd_user_id', ''),
    nullif(dkd_param_json_value->>'customer_user_id', ''),
    nullif(dkd_param_json_value->>'dkd_customer_user_id', ''),
    nullif(dkd_param_json_value->>'buyer_user_id', ''),
    nullif(dkd_param_json_value->>'user_id', ''),
    nullif(dkd_param_json_value->>'created_by', ''),
    nullif(dkd_param_json_value->>'dkd_created_by', ''),
    nullif(dkd_param_json_value->>'owner_user_id', ''),
    nullif(dkd_param_json_value->>'dkd_owner_user_id', ''),
    nullif(dkd_param_json_value->'snapshot'->>'dkd_user_id', ''),
    nullif(dkd_param_json_value->'snapshot'->>'customer_user_id', ''),
    nullif(dkd_param_json_value->'snapshot'->>'dkd_customer_user_id', ''),
    nullif(dkd_param_json_value->'snapshot'->>'buyer_user_id', ''),
    nullif(dkd_param_json_value->'snapshot'->>'user_id', ''),
    nullif(dkd_param_json_value->'snapshot'->>'created_by', ''),
    nullif(dkd_param_json_value->'dkd_payload_json'->>'dkd_user_id', ''),
    nullif(dkd_param_json_value->'dkd_payload_json'->>'customer_user_id', ''),
    nullif(dkd_param_json_value->'dkd_payload_json'->>'dkd_customer_user_id', ''),
    nullif(dkd_param_json_value->'dkd_payload_json'->>'buyer_user_id', ''),
    nullif(dkd_param_json_value->'dkd_payload_json'->>'user_id', ''),
    nullif(dkd_param_json_value->'dkd_payload_json'->>'created_by', ''),
    nullif(dkd_param_json_value->'dkd_original_order'->>'dkd_user_id', ''),
    nullif(dkd_param_json_value->'dkd_original_order'->>'customer_user_id', ''),
    nullif(dkd_param_json_value->'dkd_original_order'->>'dkd_customer_user_id', ''),
    nullif(dkd_param_json_value->'dkd_original_order'->>'buyer_user_id', ''),
    nullif(dkd_param_json_value->'dkd_original_order'->>'user_id', ''),
    nullif(dkd_param_json_value->'dkd_original_order'->>'created_by', '')
  );
$$;

revoke all on function public.dkd_json_user_id_text_dkd(jsonb) from public;
grant execute on function public.dkd_json_user_id_text_dkd(jsonb) to authenticated, service_role;

drop function if exists public.dkd_safe_uuid_text_to_uuid_dkd(text);
create function public.dkd_safe_uuid_text_to_uuid_dkd(dkd_param_user_id_text text)
returns uuid
language plpgsql
immutable
as $$
begin
  if coalesce(trim(dkd_param_user_id_text), '') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    return trim(dkd_param_user_id_text)::uuid;
  end if;
  return null;
exception
  when others then
    return null;
end;
$$;

revoke all on function public.dkd_safe_uuid_text_to_uuid_dkd(text) from public;
grant execute on function public.dkd_safe_uuid_text_to_uuid_dkd(text) to authenticated, service_role;

drop function if exists public.dkd_source_user_id_by_column_dkd(text, text, text);
create function public.dkd_source_user_id_by_column_dkd(
  dkd_param_table_name text,
  dkd_param_column_name text,
  dkd_param_filter_value text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_source_json_value jsonb := '{}'::jsonb;
  dkd_candidate_user_id_text_value text := '';
begin
  if coalesce(trim(dkd_param_table_name), '') = ''
     or coalesce(trim(dkd_param_column_name), '') = ''
     or coalesce(trim(dkd_param_filter_value), '') = '' then
    return null;
  end if;

  if not exists (
    select 1
      from information_schema.tables dkd_table_scope
     where dkd_table_scope.table_schema = 'public'
       and dkd_table_scope.table_name = dkd_param_table_name
  ) then
    return null;
  end if;

  if not exists (
    select 1
      from information_schema.columns dkd_column_scope
     where dkd_column_scope.table_schema = 'public'
       and dkd_column_scope.table_name = dkd_param_table_name
       and dkd_column_scope.column_name = dkd_param_column_name
  ) then
    return null;
  end if;

  execute format(
    'select to_jsonb(dkd_source_scope) from public.%I dkd_source_scope where dkd_source_scope.%I::text = $1 limit 1',
    dkd_param_table_name,
    dkd_param_column_name
  ) into dkd_source_json_value using dkd_param_filter_value;

  dkd_candidate_user_id_text_value := coalesce(public.dkd_json_user_id_text_dkd(coalesce(dkd_source_json_value, '{}'::jsonb)), '');
  return public.dkd_safe_uuid_text_to_uuid_dkd(dkd_candidate_user_id_text_value);
exception
  when others then
    return null;
end;
$$;

revoke all on function public.dkd_source_user_id_by_column_dkd(text, text, text) from public;
grant execute on function public.dkd_source_user_id_by_column_dkd(text, text, text) to authenticated, service_role;

drop function if exists public.dkd_courier_job_customer_user_id_dkd(bigint);
create function public.dkd_courier_job_customer_user_id_dkd(dkd_param_job_id bigint)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_job_json_value jsonb := '{}'::jsonb;
  dkd_meta_value jsonb := '{}'::jsonb;
  dkd_candidate_user_id_text_value text := '';
  dkd_cargo_shipment_id_text_value text := '';
  dkd_order_id_text_value text := '';
  dkd_target_user_id_value uuid := null;
  dkd_table_name_value text := '';
  dkd_column_name_value text := '';
begin
  if dkd_param_job_id is null or dkd_param_job_id <= 0 then
    return null;
  end if;

  if to_regclass('public.dkd_courier_jobs') is null then
    return null;
  end if;

  select to_jsonb(dkd_job_scope)
    into dkd_job_json_value
    from public.dkd_courier_jobs dkd_job_scope
   where dkd_job_scope.id = dkd_param_job_id
   limit 1;

  if dkd_job_json_value is null or dkd_job_json_value = '{}'::jsonb then
    return null;
  end if;

  dkd_meta_value := case
    when jsonb_typeof(coalesce(dkd_job_json_value->'cargo_meta', '{}'::jsonb)) = 'object' then coalesce(dkd_job_json_value->'cargo_meta', '{}'::jsonb)
    else '{}'::jsonb
  end;

  dkd_candidate_user_id_text_value := coalesce(
    public.dkd_json_user_id_text_dkd(dkd_job_json_value),
    public.dkd_json_user_id_text_dkd(dkd_meta_value),
    public.dkd_json_user_id_text_dkd(coalesce(dkd_meta_value->'dkd_original_order', '{}'::jsonb)),
    ''
  );
  dkd_target_user_id_value := public.dkd_safe_uuid_text_to_uuid_dkd(dkd_candidate_user_id_text_value);

  dkd_cargo_shipment_id_text_value := coalesce(
    nullif(dkd_job_json_value->>'cargo_shipment_id', ''),
    nullif(dkd_meta_value->>'dkd_cargo_shipment_id', ''),
    nullif(dkd_meta_value->>'cargo_shipment_id', ''),
    ''
  );

  if dkd_target_user_id_value is null and dkd_cargo_shipment_id_text_value <> '' then
    dkd_target_user_id_value := public.dkd_source_user_id_by_column_dkd('dkd_cargo_shipments', 'id', dkd_cargo_shipment_id_text_value);
  end if;

  if dkd_target_user_id_value is null then
    dkd_target_user_id_value := public.dkd_source_user_id_by_column_dkd('dkd_cargo_shipments', 'courier_job_id', dkd_param_job_id::text);
  end if;

  dkd_order_id_text_value := coalesce(
    nullif(dkd_job_json_value->>'order_id', ''),
    nullif(dkd_meta_value->>'dkd_restaurant_order_id', ''),
    nullif(dkd_meta_value->>'dkd_business_product_order_id', ''),
    nullif(dkd_meta_value->>'dkd_order_id', ''),
    nullif(dkd_meta_value->>'order_id', ''),
    nullif(dkd_meta_value->>'dkd_service_network_source_id', ''),
    nullif(dkd_meta_value->>'dkd_source_id', ''),
    nullif(dkd_meta_value->'dkd_original_order'->>'id', ''),
    nullif(dkd_meta_value->'dkd_original_order'->>'dkd_order_id', ''),
    ''
  );

  if dkd_target_user_id_value is null and dkd_order_id_text_value <> '' then
    foreach dkd_table_name_value in array array[
      'dkd_service_network_restaurant_orders',
      'dkd_service_network_requests',
      'dkd_business_product_orders',
      'dkd_cargo_shipments'
    ] loop
      foreach dkd_column_name_value in array array['id', 'dkd_order_id', 'order_id', 'dkd_source_id', 'request_id'] loop
        dkd_target_user_id_value := public.dkd_source_user_id_by_column_dkd(dkd_table_name_value, dkd_column_name_value, dkd_order_id_text_value);
        exit when dkd_target_user_id_value is not null;
      end loop;
      exit when dkd_target_user_id_value is not null;
    end loop;
  end if;

  if dkd_target_user_id_value is null then
    foreach dkd_table_name_value in array array[
      'dkd_service_network_restaurant_orders',
      'dkd_service_network_requests',
      'dkd_business_product_orders',
      'dkd_cargo_shipments'
    ] loop
      foreach dkd_column_name_value in array array['courier_job_id', 'dkd_courier_job_id', 'dkd_job_id'] loop
        dkd_target_user_id_value := public.dkd_source_user_id_by_column_dkd(dkd_table_name_value, dkd_column_name_value, dkd_param_job_id::text);
        exit when dkd_target_user_id_value is not null;
      end loop;
      exit when dkd_target_user_id_value is not null;
    end loop;
  end if;

  if dkd_target_user_id_value is not null then
    begin
      update public.dkd_courier_jobs dkd_job_scope
         set customer_user_id = coalesce(dkd_job_scope.customer_user_id, dkd_target_user_id_value),
             cargo_meta = coalesce(dkd_job_scope.cargo_meta, '{}'::jsonb) || jsonb_build_object('dkd_customer_user_id', dkd_target_user_id_value::text),
             updated_at = now()
       where dkd_job_scope.id = dkd_param_job_id;
    exception
      when others then
        null;
    end;
  end if;

  return dkd_target_user_id_value;
end;
$$;

revoke all on function public.dkd_courier_job_customer_user_id_dkd(bigint) from public;
grant execute on function public.dkd_courier_job_customer_user_id_dkd(bigint) to authenticated, service_role;

drop function if exists public.dkd_customer_status_target_tokens_dkd(uuid);
create function public.dkd_customer_status_target_tokens_dkd(dkd_param_user_id uuid)
returns table (
  user_id uuid,
  expo_push_token text,
  token text,
  dkd_expo_push_token text,
  dkd_push_segment text
)
language sql
security definer
set search_path = public
as $$
  select distinct on (coalesce(dkd_token_scope.expo_push_token, to_jsonb(dkd_token_scope)->>'token'))
    dkd_token_scope.user_id,
    coalesce(dkd_token_scope.expo_push_token, to_jsonb(dkd_token_scope)->>'token') as expo_push_token,
    coalesce(dkd_token_scope.expo_push_token, to_jsonb(dkd_token_scope)->>'token') as token,
    coalesce(dkd_token_scope.expo_push_token, to_jsonb(dkd_token_scope)->>'token') as dkd_expo_push_token,
    'customer_status'::text as dkd_push_segment
  from public.dkd_push_tokens dkd_token_scope
  where dkd_token_scope.user_id = dkd_param_user_id
    and coalesce(dkd_token_scope.is_active, false) is true
    and coalesce(dkd_token_scope.expo_push_token, to_jsonb(dkd_token_scope)->>'token', '') like 'ExponentPushToken%'
  order by coalesce(dkd_token_scope.expo_push_token, to_jsonb(dkd_token_scope)->>'token'), dkd_token_scope.updated_at desc nulls last;
$$;

revoke all on function public.dkd_customer_status_target_tokens_dkd(uuid) from public;
grant execute on function public.dkd_customer_status_target_tokens_dkd(uuid) to authenticated, service_role;

create or replace function public.dkd_courier_status_title_dkd(dkd_param_event_key text, dkd_param_job_type text)
returns text
language sql
immutable
as $$
  select case
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_accepted' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kargo Görevi Kabul Edildi'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_accepted' then 'Kurye Görevi Kabul Etti'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_picked_up' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kargo Teslim Alındı'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_picked_up' then 'Sipariş Teslim Alındı'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_delivered' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kargo Teslim Edildi'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_delivered' then 'Sipariş Teslim Edildi'
    else 'DraBornGo Sipariş Güncellemesi'
  end;
$$;

create or replace function public.dkd_courier_status_body_dkd(dkd_param_event_key text, dkd_param_job_type text, dkd_param_title text)
returns text
language sql
immutable
as $$
  select case
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_accepted' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kurye kargo görevini kabul etti ve alım noktasına ilerliyor.'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_accepted' then concat(coalesce(nullif(trim(dkd_param_title), ''), 'Sipariş'), ' için kurye görevi kabul edildi.')
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_picked_up' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kurye paketi teslim aldı ve teslimat adresine ilerliyor.'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_picked_up' then concat(coalesce(nullif(trim(dkd_param_title), ''), 'Sipariş'), ' teslim alındı. Kurye teslimat adresine ilerliyor.')
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_delivered' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kargo Siparişi başarıyla teslim edildi.'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_delivered' then concat(coalesce(nullif(trim(dkd_param_title), ''), 'Sipariş'), ' teslim edildi.')
    else 'Siparişinde yeni bir DraBornGo güncellemesi var.'
  end;
$$;

drop function if exists public.dkd_courier_job_emit_customer_status_push_dkd(bigint, text);
create function public.dkd_courier_job_emit_customer_status_push_dkd(
  dkd_param_job_id bigint,
  dkd_param_event_key text default 'courier_job_status_changed'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_job_json_value jsonb := '{}'::jsonb;
  dkd_meta_value jsonb := '{}'::jsonb;
  dkd_token_row record;
  dkd_effective_event_key_value text := lower(coalesce(nullif(trim(dkd_param_event_key), ''), 'courier_job_status_changed'));
  dkd_effective_job_type_value text := 'service_network';
  dkd_effective_title_value text := 'Sipariş';
  dkd_target_user_id_value uuid := null;
  dkd_title_value text := '';
  dkd_body_value text := '';
  dkd_payload_value jsonb := '{}'::jsonb;
  dkd_dedupe_key_value text := '';
  dkd_request_id_value bigint := null;
  dkd_queued_count_value integer := 0;
  dkd_skipped_count_value integer := 0;
begin
  if dkd_param_job_id is null or dkd_param_job_id <= 0 then
    return jsonb_build_object('ok', false, 'reason', 'dkd_invalid_job_id');
  end if;

  select to_jsonb(dkd_job_scope)
    into dkd_job_json_value
    from public.dkd_courier_jobs dkd_job_scope
   where dkd_job_scope.id = dkd_param_job_id
   limit 1;

  if dkd_job_json_value is null or dkd_job_json_value = '{}'::jsonb then
    return jsonb_build_object('ok', false, 'reason', 'dkd_job_not_found', 'dkd_job_id', dkd_param_job_id);
  end if;

  dkd_meta_value := case
    when jsonb_typeof(coalesce(dkd_job_json_value->'cargo_meta', '{}'::jsonb)) = 'object' then coalesce(dkd_job_json_value->'cargo_meta', '{}'::jsonb)
    else '{}'::jsonb
  end;

  dkd_effective_job_type_value := lower(coalesce(nullif(dkd_job_json_value->>'job_type', ''), nullif(dkd_meta_value->>'dkd_job_type', ''), 'service_network'));
  dkd_effective_title_value := coalesce(
    nullif(trim(coalesce(dkd_job_json_value->>'product_title', '')), ''),
    nullif(trim(coalesce(dkd_job_json_value->>'merchant_name', '')), ''),
    nullif(trim(coalesce(dkd_job_json_value->>'title', '')), ''),
    nullif(trim(coalesce(dkd_meta_value->>'dkd_product_title', '')), ''),
    case when dkd_effective_job_type_value in ('cargo', 'kargo') then 'Kargo Siparişi' else 'Sipariş' end
  );

  dkd_target_user_id_value := public.dkd_courier_job_customer_user_id_dkd(dkd_param_job_id);
  if dkd_target_user_id_value is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_customer_user_missing', 'dkd_job_id', dkd_param_job_id);
  end if;

  dkd_title_value := public.dkd_courier_status_title_dkd(dkd_effective_event_key_value, dkd_effective_job_type_value);
  dkd_body_value := public.dkd_courier_status_body_dkd(dkd_effective_event_key_value, dkd_effective_job_type_value, dkd_effective_title_value);
  dkd_payload_value := jsonb_build_object(
    'route', 'orders',
    'screen', 'orders',
    'targetScreen', 'orders',
    'jobId', dkd_param_job_id,
    'dkd_job_id', dkd_param_job_id,
    'dkd_event_key', dkd_effective_event_key_value,
    'dkd_job_type', dkd_effective_job_type_value,
    'dkd_pool_source', 'courier_customer_status_sql_trigger'
  );

  for dkd_token_row in
    select dkd_token_scope.expo_push_token as dkd_expo_push_token_value
      from public.dkd_customer_status_target_tokens_dkd(dkd_target_user_id_value) dkd_token_scope
  loop
    dkd_dedupe_key_value := concat(dkd_effective_event_key_value, ':', dkd_param_job_id::text, ':', dkd_target_user_id_value::text, ':', dkd_token_row.dkd_expo_push_token_value);

    insert into public.dkd_courier_status_push_audit (
      dkd_dedupe_key,
      dkd_event_key,
      dkd_job_id,
      dkd_target_user_id,
      expo_push_token,
      dkd_title,
      dkd_body,
      dkd_payload,
      dkd_send_status
    ) values (
      dkd_dedupe_key_value,
      dkd_effective_event_key_value,
      dkd_param_job_id,
      dkd_target_user_id_value,
      dkd_token_row.dkd_expo_push_token_value,
      dkd_title_value,
      dkd_body_value,
      dkd_payload_value,
      'edge_pending'
    ) on conflict (dkd_dedupe_key) do update
      set dkd_title = excluded.dkd_title,
          dkd_body = excluded.dkd_body,
          dkd_payload = excluded.dkd_payload,
          dkd_send_status = case
            when public.dkd_courier_status_push_audit.dkd_send_status in ('edge_sent', 'sent', 'delivered') then public.dkd_courier_status_push_audit.dkd_send_status
            else excluded.dkd_send_status
          end,
          dkd_send_error = null;

    begin
      select net.http_post(
        url := 'https://exp.host/--/api/v2/push/send',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Accept', 'application/json',
          'Accept-Encoding', 'gzip, deflate'
        ),
        body := jsonb_build_object(
          'to', dkd_token_row.dkd_expo_push_token_value,
          'sound', 'default',
          'title', dkd_title_value,
          'body', dkd_body_value,
          'channelId', 'draborngo-core',
          'data', dkd_payload_value
        ),
        timeout_milliseconds := 1500
      ) into dkd_request_id_value;

      update public.dkd_courier_status_push_audit
         set dkd_send_status = 'queued_pg_net',
             dkd_send_error = null,
             dkd_sent_at = timezone('utc', now())
       where dkd_dedupe_key = dkd_dedupe_key_value
         and dkd_send_status <> 'edge_sent';

      dkd_queued_count_value := dkd_queued_count_value + 1;
    exception
      when invalid_schema_name or undefined_function then
        update public.dkd_courier_status_push_audit
           set dkd_send_status = 'edge_pending',
               dkd_send_error = 'pg_net yok; Edge Function doğrudan gönderecek.'
         where dkd_dedupe_key = dkd_dedupe_key_value
           and dkd_send_status <> 'edge_sent';
        dkd_skipped_count_value := dkd_skipped_count_value + 1;
      when others then
        update public.dkd_courier_status_push_audit
           set dkd_send_status = 'edge_pending',
               dkd_send_error = sqlerrm
         where dkd_dedupe_key = dkd_dedupe_key_value
           and dkd_send_status <> 'edge_sent';
        dkd_skipped_count_value := dkd_skipped_count_value + 1;
    end;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'dkd_job_id', dkd_param_job_id,
    'dkd_event_key', dkd_effective_event_key_value,
    'dkd_target_user_id', dkd_target_user_id_value,
    'dkd_queued_count', dkd_queued_count_value,
    'dkd_skipped_count', dkd_skipped_count_value
  );
end;
$$;

revoke all on function public.dkd_courier_job_emit_customer_status_push_dkd(bigint, text) from public;
grant execute on function public.dkd_courier_job_emit_customer_status_push_dkd(bigint, text) to authenticated, service_role;

drop function if exists public.dkd_courier_job_status_push_after_update_dkd();
create function public.dkd_courier_job_status_push_after_update_dkd()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_old_status_value text := lower(coalesce(old.status, ''));
  dkd_new_status_value text := lower(coalesce(new.status, ''));
  dkd_old_pickup_status_value text := lower(coalesce(old.pickup_status, ''));
  dkd_new_pickup_status_value text := lower(coalesce(new.pickup_status, ''));
  dkd_event_key_value text := '';
begin
  if new.id is null or coalesce(new.is_active, true) is not true then
    return new;
  end if;

  if dkd_old_status_value not in ('completed', 'delivered', 'done', 'finished')
     and (dkd_new_status_value in ('completed', 'delivered', 'done', 'finished') or dkd_new_pickup_status_value = 'delivered') then
    dkd_event_key_value := 'courier_job_delivered';
  elsif dkd_old_status_value not in ('picked_up', 'to_customer', 'delivering')
     and dkd_old_pickup_status_value not in ('picked_up', 'delivered')
     and (dkd_new_status_value in ('picked_up', 'to_customer', 'delivering') or dkd_new_pickup_status_value = 'picked_up') then
    dkd_event_key_value := 'courier_job_picked_up';
  elsif dkd_old_status_value not in ('accepted', 'assigned', 'to_business')
     and (
       dkd_new_status_value in ('accepted', 'assigned', 'to_business')
       or (old.assigned_user_id is distinct from new.assigned_user_id and new.assigned_user_id is not null)
     ) then
    dkd_event_key_value := 'courier_job_accepted';
  end if;

  if dkd_event_key_value <> '' then
    perform public.dkd_courier_job_emit_customer_status_push_dkd(new.id, dkd_event_key_value);
  end if;

  return new;
exception
  when others then
    return new;
end;
$$;

revoke all on function public.dkd_courier_job_status_push_after_update_dkd() from public;
grant execute on function public.dkd_courier_job_status_push_after_update_dkd() to service_role;

do $$
begin
  if to_regclass('public.dkd_courier_jobs') is not null then
    execute 'drop trigger if exists dkd_courier_job_status_push_after_update_trigger on public.dkd_courier_jobs';
    execute 'create trigger dkd_courier_job_status_push_after_update_trigger after update of status, pickup_status, assigned_user_id on public.dkd_courier_jobs for each row execute function public.dkd_courier_job_status_push_after_update_dkd()';
  end if;
end $$;

notify pgrst, 'reload schema';

commit;
