-- DraBornGo DKD courier/cargo push notification fix
-- Date: 2026-05-19
-- Purpose:
-- 1) Provide courier target token RPC used by send-courier-order-alert for Gönderi Paneli/cargo orders.
-- 2) Provide customer status push RPC used by app when courier accepts, picks up, and delivers restaurant/cargo jobs.
-- Safe rerun: does not delete existing order or profile data.

begin;

do $$
begin
  create extension if not exists pg_net;
exception
  when others then
    null;
end $$;

create table if not exists public.dkd_courier_status_push_audit (
  dkd_audit_id bigint generated by default as identity primary key,
  dkd_dedupe_key text not null,
  dkd_event_key text not null,
  dkd_job_id bigint not null,
  dkd_target_user_id uuid null,
  expo_push_token text not null,
  dkd_title text not null,
  dkd_body text not null,
  dkd_payload jsonb not null default '{}'::jsonb,
  dkd_send_status text not null default 'pending',
  dkd_send_error text null,
  dkd_created_at timestamptz not null default timezone('utc', now()),
  dkd_sent_at timestamptz null
);

alter table public.dkd_courier_status_push_audit enable row level security;
create unique index if not exists dkd_courier_status_push_audit_dedupe_idx
  on public.dkd_courier_status_push_audit(dkd_dedupe_key);
create index if not exists dkd_courier_status_push_audit_job_event_idx
  on public.dkd_courier_status_push_audit(dkd_job_id, dkd_event_key, dkd_created_at desc);
grant select, insert, update on public.dkd_courier_status_push_audit to service_role;

create or replace function public.dkd_courier_job_push_target_tokens()
returns table(
  user_id uuid,
  expo_push_token text,
  dkd_push_segment text
)
language sql
security definer
set search_path = public
as $$
  select
    dkd_token_scope.user_id,
    dkd_token_scope.expo_push_token,
    'courier_licensed'::text as dkd_push_segment
  from public.dkd_push_tokens dkd_token_scope
  left join public.dkd_profiles dkd_profile_scope
    on dkd_profile_scope.user_id = dkd_token_scope.user_id
  where dkd_token_scope.is_active = true
    and nullif(trim(coalesce(dkd_token_scope.expo_push_token, '')), '') is not null
    and (
      public.dkd_urgent_courier_license_active_dkd(dkd_token_scope.user_id) is true
      or lower(coalesce(dkd_profile_scope.courier_status, '')) in ('approved', 'active', 'aktif', 'onayli', 'onaylı')
    )
  group by dkd_token_scope.user_id, dkd_token_scope.expo_push_token;
$$;

revoke all on function public.dkd_courier_job_push_target_tokens() from public;
grant execute on function public.dkd_courier_job_push_target_tokens() to service_role, authenticated;

create or replace function public.dkd_courier_status_title_dkd(dkd_param_event_key text, dkd_param_job_type text)
returns text
language sql
immutable
as $$
  select case
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_accepted' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kargo Görevi Kabul Edildi'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_accepted' then 'Kurye Görevi Kabul Etti'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_picked_up' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kargo Teslim Alındı'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_picked_up' then 'Sipariş Teslim Alındı'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_delivered' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kargo Teslim Edildi'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_delivered' then 'Sipariş Teslim Edildi'
    else 'DraBornGo Sipariş Güncellemesi'
  end;
$$;

create or replace function public.dkd_courier_status_body_dkd(dkd_param_event_key text, dkd_param_job_type text, dkd_param_title text)
returns text
language sql
immutable
as $$
  select case
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_accepted' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kurye kargo görevini kabul etti ve alım noktasına ilerliyor.'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_accepted' then concat(coalesce(nullif(trim(dkd_param_title), ''), 'Sipariş'), ' için kurye görevi kabul edildi.')
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_picked_up' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kurye paketi teslim aldı ve teslimat adresine ilerliyor.'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_picked_up' then concat(coalesce(nullif(trim(dkd_param_title), ''), 'Sipariş'), ' teslim alındı. Kurye teslimat adresine ilerliyor.')
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_delivered' and lower(coalesce(dkd_param_job_type, '')) in ('cargo', 'kargo') then 'Kargo Siparişi başarıyla teslim edildi.'
    when lower(coalesce(dkd_param_event_key, '')) = 'courier_job_delivered' then concat(coalesce(nullif(trim(dkd_param_title), ''), 'Sipariş'), ' teslim edildi.')
    else 'Siparişinde yeni bir DraBornGo güncellemesi var.'
  end;
$$;

create or replace function public.dkd_courier_job_emit_customer_status_push_dkd(
  dkd_param_job_id bigint,
  dkd_param_event_key text default 'courier_job_status_changed'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  dkd_job_row record;
  dkd_target_row record;
  dkd_effective_event_key_value text := lower(coalesce(nullif(trim(dkd_param_event_key), ''), 'courier_job_status_changed'));
  dkd_effective_job_type_value text := 'service_network';
  dkd_effective_title_value text := 'Sipariş';
  dkd_target_user_id_value uuid;
  dkd_title_value text;
  dkd_body_value text;
  dkd_payload_value jsonb;
  dkd_dedupe_key_value text;
  dkd_request_id_value bigint;
  dkd_queued_count_value integer := 0;
  dkd_skipped_count_value integer := 0;
begin
  if dkd_param_job_id is null or dkd_param_job_id <= 0 then
    return jsonb_build_object('ok', false, 'reason', 'dkd_invalid_job_id');
  end if;

  select dkd_job_scope.*
    into dkd_job_row
    from public.dkd_courier_jobs dkd_job_scope
   where dkd_job_scope.id = dkd_param_job_id
   limit 1;

  if dkd_job_row is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_job_not_found', 'dkd_job_id', dkd_param_job_id);
  end if;

  dkd_effective_job_type_value := lower(coalesce(dkd_job_row.job_type, 'service_network'));
  dkd_effective_title_value := coalesce(
    nullif(trim(coalesce(dkd_job_row.product_title, '')), ''),
    nullif(trim(coalesce(dkd_job_row.merchant_name, '')), ''),
    nullif(trim(coalesce(dkd_job_row.title, '')), ''),
    case when dkd_effective_job_type_value in ('cargo', 'kargo') then 'Kargo Siparişi' else 'Sipariş' end
  );
  dkd_target_user_id_value := dkd_job_row.customer_user_id;

  if dkd_target_user_id_value is null and dkd_job_row.cargo_shipment_id is not null and to_regclass('public.dkd_cargo_shipments') is not null then
    select dkd_shipment_scope.customer_user_id
      into dkd_target_user_id_value
      from public.dkd_cargo_shipments dkd_shipment_scope
     where dkd_shipment_scope.id = dkd_job_row.cargo_shipment_id
     limit 1;
  end if;

  if dkd_target_user_id_value is null then
    return jsonb_build_object('ok', false, 'reason', 'dkd_customer_user_missing', 'dkd_job_id', dkd_param_job_id);
  end if;

  dkd_title_value := public.dkd_courier_status_title_dkd(dkd_effective_event_key_value, dkd_effective_job_type_value);
  dkd_body_value := public.dkd_courier_status_body_dkd(dkd_effective_event_key_value, dkd_effective_job_type_value, dkd_effective_title_value);
  dkd_payload_value := jsonb_build_object(
    'route', 'orders',
    'screen', 'orders',
    'targetScreen', 'orders',
    'jobId', dkd_param_job_id,
    'dkd_job_id', dkd_param_job_id,
    'dkd_event_key', dkd_effective_event_key_value,
    'dkd_job_type', dkd_effective_job_type_value,
    'dkd_pool_source', 'courier_customer_status'
  );

  for dkd_target_row in
    select dkd_token_scope.expo_push_token
      from public.dkd_push_tokens dkd_token_scope
     where dkd_token_scope.user_id = dkd_target_user_id_value
       and dkd_token_scope.is_active = true
       and nullif(trim(coalesce(dkd_token_scope.expo_push_token, '')), '') is not null
     group by dkd_token_scope.expo_push_token
  loop
    dkd_dedupe_key_value := concat(dkd_effective_event_key_value, ':', dkd_param_job_id::text, ':', dkd_target_user_id_value::text, ':', md5(dkd_target_row.expo_push_token));

    insert into public.dkd_courier_status_push_audit (
      dkd_dedupe_key,
      dkd_event_key,
      dkd_job_id,
      dkd_target_user_id,
      expo_push_token,
      dkd_title,
      dkd_body,
      dkd_payload,
      dkd_send_status
    ) values (
      dkd_dedupe_key_value,
      dkd_effective_event_key_value,
      dkd_param_job_id,
      dkd_target_user_id_value,
      dkd_target_row.expo_push_token,
      dkd_title_value,
      dkd_body_value,
      dkd_payload_value,
      'pending'
    ) on conflict (dkd_dedupe_key) do nothing;

    if not found then
      dkd_skipped_count_value := dkd_skipped_count_value + 1;
      continue;
    end if;

    begin
      select net.http_post(
        url := 'https://exp.host/--/api/v2/push/send',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Accept', 'application/json',
          'Accept-Encoding', 'gzip, deflate'
        ),
        body := jsonb_build_object(
          'to', dkd_target_row.expo_push_token,
          'sound', 'default',
          'title', dkd_title_value,
          'body', dkd_body_value,
          'channelId', 'draborngo-core',
          'data', dkd_payload_value
        ),
        timeout_milliseconds := 1500
      ) into dkd_request_id_value;

      update public.dkd_courier_status_push_audit
         set dkd_send_status = 'queued_pg_net',
             dkd_send_error = null,
             dkd_sent_at = timezone('utc', now())
       where dkd_dedupe_key = dkd_dedupe_key_value;

      dkd_queued_count_value := dkd_queued_count_value + 1;
    exception
      when invalid_schema_name or undefined_function then
        update public.dkd_courier_status_push_audit
           set dkd_send_status = 'pg_net_missing',
               dkd_send_error = 'pg_net extension açık değil veya net.http_post kullanılamıyor.'
         where dkd_dedupe_key = dkd_dedupe_key_value;
        dkd_skipped_count_value := dkd_skipped_count_value + 1;
      when others then
        update public.dkd_courier_status_push_audit
           set dkd_send_status = 'failed',
               dkd_send_error = sqlerrm
         where dkd_dedupe_key = dkd_dedupe_key_value;
        dkd_skipped_count_value := dkd_skipped_count_value + 1;
    end;
  end loop;

  return jsonb_build_object(
    'ok', true,
    'dkd_job_id', dkd_param_job_id,
    'dkd_event_key', dkd_effective_event_key_value,
    'dkd_target_user_id', dkd_target_user_id_value,
    'dkd_queued_count', dkd_queued_count_value,
    'dkd_skipped_count', dkd_skipped_count_value
  );
end;
$$;

revoke all on function public.dkd_courier_job_emit_customer_status_push_dkd(bigint, text) from public;
grant execute on function public.dkd_courier_job_emit_customer_status_push_dkd(bigint, text) to authenticated, service_role;

commit;
