-- DraBornGo v0.0.12: retire legacy Hizmet Ağı request system, add courier earnings, direct admin support and admin user management.

-- Retire legacy category-based Hizmet Ağı runtime/data while preserving cargo delivery.
drop trigger if exists dkd_courier_jobs_sync_service_network_status_au on public.dkd_courier_jobs;
drop trigger if exists dkd_service_network_requests_to_courier_jobs_ai on public.dkd_service_network_requests;
drop trigger if exists dkd_touch_service_network_requests_updated_at on public.dkd_service_network_requests;

delete from public.dkd_courier_jobs
where lower(coalesce(job_type,'')) = 'service_network'
   or coalesce(cargo_meta->>'dkd_service_network_source_id','') <> ''
   or coalesce(cargo_meta->>'dkd_pool_source','') = 'service_network';

drop function if exists public.dkd_courier_pool_sync_service_network_status_dkd() cascade;
drop function if exists public.dkd_service_network_cleanup_deleted_orders_dkd() cascade;
drop function if exists public.dkd_service_network_delete_completed_order_dkd(text,text) cascade;
drop function if exists public.dkd_service_network_emit_courier_job_push_dkd(bigint,text) cascade;
drop function if exists public.dkd_service_network_my_orders_dkd(integer) cascade;
drop function if exists public.dkd_service_network_order_id_text_dkd(jsonb) cascade;
drop function if exists public.dkd_service_network_push_health_check_dkd() cascade;
drop function if exists public.dkd_service_network_request_to_courier_job_dkd() cascade;
drop function if exists public.dkd_touch_service_network_updated_at() cascade;

drop table if exists public.dkd_service_network_customer_notification_audit cascade;
drop table if exists public.dkd_service_network_requests cascade;

create or replace function public.dkd_courier_job_customer_user_id_dkd(dkd_param_job_id bigint)
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  dkd_job_row public.dkd_courier_jobs%rowtype;
  dkd_target_user_id_value uuid;
begin
  if dkd_param_job_id is null or dkd_param_job_id <= 0 then return null; end if;
  select * into dkd_job_row from public.dkd_courier_jobs where id = dkd_param_job_id limit 1;
  if not found then return null; end if;
  dkd_target_user_id_value := dkd_job_row.customer_user_id;
  if dkd_target_user_id_value is null and dkd_job_row.cargo_shipment_id is not null then
    select customer_user_id into dkd_target_user_id_value
    from public.dkd_cargo_shipments
    where id = dkd_job_row.cargo_shipment_id
    limit 1;
  end if;
  if dkd_target_user_id_value is not null and dkd_job_row.customer_user_id is null then
    update public.dkd_courier_jobs
       set customer_user_id = dkd_target_user_id_value,
           cargo_meta = coalesce(cargo_meta,'{}'::jsonb) || jsonb_build_object('dkd_customer_user_id',dkd_target_user_id_value::text),
           updated_at = now()
     where id = dkd_param_job_id;
  end if;
  return dkd_target_user_id_value;
end;
$function$;

-- Courier online work sessions and earnings analytics.
create table if not exists public.dkd_courier_online_sessions (
  dkd_id bigint generated by default as identity primary key,
  dkd_user_id uuid not null,
  dkd_started_at timestamptz not null default now(),
  dkd_ended_at timestamptz,
  dkd_duration_seconds bigint,
  dkd_country text,
  dkd_city text,
  dkd_region text,
  dkd_created_at timestamptz not null default now(),
  constraint dkd_courier_online_sessions_duration_check check (dkd_duration_seconds is null or dkd_duration_seconds >= 0)
);
create index if not exists dkd_courier_online_sessions_user_started_idx on public.dkd_courier_online_sessions(dkd_user_id, dkd_started_at desc);
create unique index if not exists dkd_courier_online_sessions_one_open_idx on public.dkd_courier_online_sessions(dkd_user_id) where dkd_ended_at is null;
alter table public.dkd_courier_online_sessions enable row level security;
drop policy if exists dkd_courier_online_sessions_self_select on public.dkd_courier_online_sessions;
create policy dkd_courier_online_sessions_self_select on public.dkd_courier_online_sessions for select to authenticated using (dkd_user_id = auth.uid() or public.dkd_is_admin());

insert into public.dkd_courier_online_sessions(dkd_user_id, dkd_started_at, dkd_country, dkd_city, dkd_region)
select p.user_id, coalesce(p.dkd_courier_last_online_at, now()), p.dkd_courier_online_country, p.dkd_courier_online_city, p.dkd_courier_online_region
from public.dkd_profiles p
where p.dkd_courier_online is true
  and not exists (select 1 from public.dkd_courier_online_sessions s where s.dkd_user_id=p.user_id and s.dkd_ended_at is null)
on conflict do nothing;

create or replace function public.dkd_close_courier_online_session_dkd(dkd_param_user_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  update public.dkd_courier_online_sessions
     set dkd_ended_at = now(),
         dkd_duration_seconds = greatest(0, floor(extract(epoch from (now() - dkd_started_at)))::bigint)
   where dkd_user_id = dkd_param_user_id
     and dkd_ended_at is null;
end;
$function$;

create or replace function public.dkd_courier_online_set_dkd(
  dkd_param_online boolean,
  dkd_param_country text default 'Türkiye',
  dkd_param_city text default 'Ankara',
  dkd_param_region text default '',
  dkd_param_live_lat numeric default null,
  dkd_param_live_lng numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','auth'
as $function$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_next_job_id_value bigint := null;
  dkd_active_delivery_job_id_value bigint := null;
  dkd_existing_offer_job_id_value bigint := null;
  dkd_safe_country_value text := coalesce(nullif(trim(dkd_param_country), ''), 'Türkiye');
  dkd_safe_city_value text := coalesce(nullif(trim(dkd_param_city), ''), 'Ankara');
  dkd_safe_region_value text := coalesce(nullif(trim(dkd_param_region), ''), '');
begin
  if dkd_user_id_value is null then
    return jsonb_build_object('dkd_ok_value', false, 'dkd_reason_value', 'auth_required');
  end if;
  insert into public.dkd_profiles (user_id) values (dkd_user_id_value) on conflict (user_id) do nothing;
  select j.id into dkd_active_delivery_job_id_value
  from public.dkd_courier_jobs j
  where j.assigned_user_id = dkd_user_id_value
    and coalesce(j.is_active, true) = true
    and lower(coalesce(j.status, '')) in ('accepted','assigned','to_pickup','picked_up','to_customer','delivering')
    and lower(coalesce(j.pickup_status, '')) not in ('delivered','cancelled','canceled')
  order by j.updated_at desc nulls last, j.created_at desc nulls last
  limit 1;
  if dkd_active_delivery_job_id_value is not null then
    perform public.dkd_close_courier_online_session_dkd(dkd_user_id_value);
    update public.dkd_profiles
       set dkd_courier_online=false,
           dkd_courier_auto_assigned_job_id=dkd_active_delivery_job_id_value,
           dkd_courier_last_online_at=now()
     where user_id=dkd_user_id_value;
    return jsonb_build_object('dkd_ok_value',true,'dkd_online_value',false,'dkd_has_active_delivery_value',true,'dkd_assigned_job_id',dkd_active_delivery_job_id_value,'assigned_job_id',dkd_active_delivery_job_id_value);
  end if;
  if dkd_param_online is not true then
    perform public.dkd_close_courier_online_session_dkd(dkd_user_id_value);
    update public.dkd_profiles
       set dkd_courier_online=false, dkd_courier_auto_assigned_job_id=null, dkd_courier_last_online_at=now()
     where user_id=dkd_user_id_value;
    return jsonb_build_object('dkd_ok_value',true,'dkd_online_value',false,'dkd_assigned_job_id',null,'assigned_job_id',null);
  end if;
  if not exists (select 1 from public.dkd_profiles p where p.user_id=dkd_user_id_value and coalesce(p.courier_status,'')='approved') then
    return jsonb_build_object('dkd_ok_value',false,'dkd_reason_value','courier_not_approved');
  end if;
  insert into public.dkd_courier_online_sessions(dkd_user_id,dkd_started_at,dkd_country,dkd_city,dkd_region)
  values(dkd_user_id_value,now(),dkd_safe_country_value,dkd_safe_city_value,dkd_safe_region_value)
  on conflict do nothing;
  update public.dkd_profiles
     set dkd_courier_online=true,
         dkd_courier_online_country=dkd_safe_country_value,
         dkd_courier_online_city=dkd_safe_city_value,
         dkd_courier_online_region=dkd_safe_region_value,
         dkd_courier_online_lat=dkd_param_live_lat,
         dkd_courier_online_lng=dkd_param_live_lng,
         dkd_courier_last_online_at=now()
   where user_id=dkd_user_id_value;
  select j.id into dkd_existing_offer_job_id_value
  from public.dkd_courier_jobs j
  where j.assigned_user_id=dkd_user_id_value
    and coalesce(j.is_active,true)=true
    and lower(coalesce(j.status,'')) in ('dkd_auto_assigned','dkd_assigned_offer','courier_offer','auto_assigned','assigned_offer')
  order by j.updated_at desc nulls last, j.created_at desc nulls last limit 1;
  if dkd_existing_offer_job_id_value is not null then
    update public.dkd_profiles set dkd_courier_auto_assigned_job_id=dkd_existing_offer_job_id_value where user_id=dkd_user_id_value;
    return jsonb_build_object('dkd_ok_value',true,'dkd_online_value',true,'dkd_assigned_job_id',dkd_existing_offer_job_id_value,'assigned_job_id',dkd_existing_offer_job_id_value);
  end if;
  select j.id into dkd_next_job_id_value
  from public.dkd_courier_jobs j
  where j.assigned_user_id is null
    and coalesce(j.is_active,true)=true
    and lower(coalesce(j.status,'open')) in ('open','ready','published')
    and not public.dkd_jsonb_array_has_text_dkd(coalesce(j.cargo_meta,'{}'::jsonb)->'dkd_rejected_courier_user_ids',dkd_user_id_value::text)
    and public.dkd_region_match_dkd(j.dkd_country,j.dkd_city,j.dkd_region,dkd_safe_country_value,dkd_safe_city_value,dkd_safe_region_value)
  order by case when dkd_param_live_lat is not null and dkd_param_live_lng is not null and j.pickup_lat is not null and j.pickup_lng is not null then public.dkd_distance_km_between(dkd_param_live_lat,dkd_param_live_lng,j.pickup_lat,j.pickup_lng) else null end asc nulls last,
           j.updated_at desc nulls last, j.created_at desc
  limit 1 for update skip locked;
  if dkd_next_job_id_value is not null then
    update public.dkd_courier_jobs j
       set assigned_user_id=dkd_user_id_value,
           status='dkd_assigned_offer',
           dkd_auto_assigned_at=now(),
           dkd_assignment_expires_at=now()+interval '4 minutes',
           cargo_meta=coalesce(j.cargo_meta,'{}'::jsonb)||jsonb_build_object('dkd_auto_assigned_to',dkd_user_id_value::text,'dkd_auto_assigned_at',now()),
           updated_at=now()
     where j.id=dkd_next_job_id_value;
  end if;
  update public.dkd_profiles set dkd_courier_auto_assigned_job_id=dkd_next_job_id_value where user_id=dkd_user_id_value;
  return jsonb_build_object('dkd_ok_value',true,'dkd_online_value',true,'dkd_has_active_delivery_value',false,'dkd_assigned_job_id',dkd_next_job_id_value,'assigned_job_id',dkd_next_job_id_value);
end;
$function$;

create or replace function public.dkd_courier_earnings_summary_dkd(dkd_param_user_id uuid default null)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','auth'
as $function$
declare
  dkd_auth_user_id uuid := auth.uid();
  dkd_target_user_id uuid := coalesce(dkd_param_user_id, auth.uid());
  dkd_is_admin_value boolean := coalesce(public.dkd_is_admin(),false);
  dkd_day_start timestamptz := (date_trunc('day', now() at time zone 'Europe/Istanbul') at time zone 'Europe/Istanbul');
  dkd_week_start timestamptz := (date_trunc('week', now() at time zone 'Europe/Istanbul') at time zone 'Europe/Istanbul');
  dkd_month_start timestamptz := (date_trunc('month', now() at time zone 'Europe/Istanbul') at time zone 'Europe/Istanbul');
  dkd_result jsonb;
begin
  if dkd_auth_user_id is null or dkd_target_user_id is null then raise exception 'dkd_auth_required'; end if;
  if dkd_target_user_id <> dkd_auth_user_id and not dkd_is_admin_value then raise exception 'dkd_admin_required'; end if;
  with periods as (
    select 'daily'::text as key, dkd_day_start as start_at, now() as end_at
    union all select 'weekly', dkd_week_start, now()
    union all select 'monthly', dkd_month_start, now()
  ), stats as (
    select p.key,
      coalesce((select sum(coalesce(j.fee_tl,0)) from public.dkd_courier_jobs j where j.assigned_user_id=dkd_target_user_id and coalesce(j.completed_at,j.updated_at)>=p.start_at and coalesce(j.completed_at,j.updated_at)<=p.end_at and (j.completed_at is not null or lower(coalesce(j.status,'')) in ('completed','delivered'))),0)::numeric as earnings_tl,
      coalesce((select count(*) from public.dkd_courier_jobs j where j.assigned_user_id=dkd_target_user_id and coalesce(j.completed_at,j.updated_at)>=p.start_at and coalesce(j.completed_at,j.updated_at)<=p.end_at and (j.completed_at is not null or lower(coalesce(j.status,'')) in ('completed','delivered'))),0)::bigint as completed_jobs,
      coalesce((select sum(greatest(0,extract(epoch from (least(coalesce(s.dkd_ended_at,now()),p.end_at)-greatest(s.dkd_started_at,p.start_at))))) from public.dkd_courier_online_sessions s where s.dkd_user_id=dkd_target_user_id and s.dkd_started_at < p.end_at and coalesce(s.dkd_ended_at,now()) > p.start_at),0)::numeric as online_seconds
    from periods p
  )
  select jsonb_object_agg(key,jsonb_build_object(
    'dkd_earnings_tl',round(earnings_tl,2),
    'dkd_completed_jobs',completed_jobs,
    'dkd_online_seconds',floor(online_seconds),
    'dkd_online_hours',round(online_seconds/3600.0,2),
    'dkd_hourly_tl',case when online_seconds>0 then round(earnings_tl/(online_seconds/3600.0),2) else 0 end
  )) into dkd_result from stats;
  return coalesce(dkd_result,'{}'::jsonb) || jsonb_build_object(
    'dkd_user_id',dkd_target_user_id,
    'dkd_generated_at',now(),
    'dkd_is_online',coalesce((select p.dkd_courier_online from public.dkd_profiles p where p.user_id=dkd_target_user_id),false),
    'dkd_lifetime_earnings_tl',coalesce((select round(sum(coalesce(j.fee_tl,0)),2) from public.dkd_courier_jobs j where j.assigned_user_id=dkd_target_user_id and (j.completed_at is not null or lower(coalesce(j.status,'')) in ('completed','delivered'))),0),
    'dkd_lifetime_completed_jobs',coalesce((select count(*) from public.dkd_courier_jobs j where j.assigned_user_id=dkd_target_user_id and (j.completed_at is not null or lower(coalesce(j.status,'')) in ('completed','delivered'))),0)
  );
end;
$function$;

grant execute on function public.dkd_courier_earnings_summary_dkd(uuid) to authenticated;

-- Direct DrabornEagle support conversation for authenticated users.
create or replace function public.dkd_support_primary_thread_dkd()
returns jsonb
language plpgsql
security definer
set search_path to 'public','auth'
as $function$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_thread_id_value uuid;
  dkd_admin_user_id_value uuid;
begin
  if dkd_user_id_value is null then raise exception 'dkd_auth_required'; end if;
  if public.dkd_is_admin() then return jsonb_build_object('dkd_is_admin',true); end if;
  select a.user_id into dkd_admin_user_id_value
  from public.dkd_admin_users a
  left join public.dkd_profiles p on p.user_id=a.user_id
  order by case when lower(coalesce(p.nickname,''))='draborneagle' then 0 else 1 end, a.created_at
  limit 1;
  select t.dkd_id into dkd_thread_id_value
  from public.dkd_support_threads t
  where t.dkd_user_id=dkd_user_id_value and t.dkd_topic_key='dkd_direct_admin'
  order by t.dkd_created_at asc
  limit 1;
  if dkd_thread_id_value is null then
    insert into public.dkd_support_threads(
      dkd_user_id,dkd_ticket_code,dkd_topic_key,dkd_topic_title,dkd_priority_key,dkd_status_key,dkd_status_title,dkd_source_key,dkd_last_message_text,dkd_needs_admin_reply,dkd_admin_needed
    ) values (
      dkd_user_id_value,
      'DKD-CHAT-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10)),
      'dkd_direct_admin','DrabornEagle Destek','dkd_normal','dkd_open','DrabornEagle destek hattı','dkd_mobile_direct_support','',false,false
    ) returning dkd_id into dkd_thread_id_value;
  end if;
  return jsonb_build_object('dkd_is_admin',false,'dkd_thread_id',dkd_thread_id_value,'dkd_admin_user_id',dkd_admin_user_id_value,'dkd_admin_title','DrabornEagle','dkd_admin_badge','Admin');
end;
$function$;

create or replace function public.dkd_support_thread_messages_dkd(dkd_param_thread_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','auth'
as $function$
declare
  dkd_user_id_value uuid := auth.uid();
  dkd_is_admin_value boolean := coalesce(public.dkd_is_admin(),false);
  dkd_owner_value uuid;
  dkd_result jsonb;
begin
  if dkd_user_id_value is null then raise exception 'dkd_auth_required'; end if;
  select dkd_user_id into dkd_owner_value from public.dkd_support_threads where dkd_id=dkd_param_thread_id;
  if dkd_owner_value is null or (dkd_owner_value<>dkd_user_id_value and not dkd_is_admin_value) then raise exception 'dkd_support_thread_forbidden'; end if;
  select coalesce(jsonb_agg(jsonb_build_object('dkd_id',m.dkd_id,'dkd_thread_id',m.dkd_thread_id,'dkd_sender_key',m.dkd_sender_key,'dkd_sender_title',m.dkd_sender_title,'dkd_message_text',m.dkd_message_text,'dkd_created_at',m.dkd_created_at) order by m.dkd_created_at),'[]'::jsonb)
    into dkd_result
  from public.dkd_support_messages m where m.dkd_thread_id=dkd_param_thread_id;
  return dkd_result;
end;
$function$;

create or replace function public.dkd_support_admin_threads_dkd(dkd_param_search text default '', dkd_param_limit integer default 80)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','auth'
as $function$
declare dkd_result jsonb;
begin
  if not public.dkd_is_admin() then raise exception 'dkd_admin_required'; end if;
  select coalesce(jsonb_agg(to_jsonb(x) order by x.dkd_updated_at desc),'[]'::jsonb) into dkd_result
  from (
    select t.dkd_id as dkd_thread_id,t.dkd_user_id,t.dkd_ticket_code,t.dkd_status_key,t.dkd_status_title,t.dkd_last_message_text,t.dkd_created_at,t.dkd_updated_at,
           coalesce(p.nickname,'Kullanıcı') as dkd_nickname,coalesce(p.dbg_id,'') as dkd_dbg_id,coalesce(u.email,'') as dkd_email,coalesce(u.phone,'') as dkd_phone
    from public.dkd_support_threads t
    left join public.dkd_profiles p on p.user_id=t.dkd_user_id
    left join auth.users u on u.id=t.dkd_user_id
    where t.dkd_topic_key='dkd_direct_admin'
      and (trim(coalesce(dkd_param_search,''))='' or coalesce(p.nickname,'') ilike '%'||trim(dkd_param_search)||'%' or coalesce(u.email,'') ilike '%'||trim(dkd_param_search)||'%' or coalesce(p.dbg_id,'') ilike '%'||trim(dkd_param_search)||'%')
    order by t.dkd_updated_at desc
    limit least(greatest(coalesce(dkd_param_limit,80),1),200)
  ) x;
  return dkd_result;
end;
$function$;

grant execute on function public.dkd_support_primary_thread_dkd() to authenticated;
grant execute on function public.dkd_support_thread_messages_dkd(uuid) to authenticated;
grant execute on function public.dkd_support_admin_threads_dkd(text,integer) to authenticated;

create or replace function public.dkd_send_support_thread_message(dkd_param_thread_id uuid, dkd_param_message_text text)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  dkd_var_auth_user_id uuid := auth.uid();
  dkd_var_is_admin boolean := coalesce(public.dkd_is_admin(), false);
  dkd_var_thread_record public.dkd_support_threads%rowtype;
  dkd_var_clean_message_text text;
  dkd_var_sender_key text;
  dkd_var_sender_title text;
  dkd_var_message_owner_id uuid;
  dkd_var_next_status_key text;
  dkd_var_next_status_title text;
  dkd_var_message_id uuid;
begin
  if dkd_var_auth_user_id is null then raise exception 'dkd_auth_required'; end if;
  dkd_var_clean_message_text := trim(coalesce(dkd_param_message_text, ''));
  if length(dkd_var_clean_message_text) < 1 then raise exception 'dkd_support_message_too_short'; end if;
  select t.* into dkd_var_thread_record from public.dkd_support_threads t where t.dkd_id=dkd_param_thread_id and (t.dkd_user_id=dkd_var_auth_user_id or dkd_var_is_admin) limit 1;
  if not found then raise exception 'dkd_support_thread_not_found'; end if;
  if dkd_var_is_admin then
    dkd_var_sender_key:='dkd_admin'; dkd_var_sender_title:='DrabornEagle • Admin'; dkd_var_message_owner_id:=dkd_var_thread_record.dkd_user_id;
    dkd_var_next_status_key:='dkd_answered'; dkd_var_next_status_title:='DrabornEagle yanıtladı';
  else
    dkd_var_sender_key:='dkd_customer'; dkd_var_sender_title:='Kullanıcı'; dkd_var_message_owner_id:=dkd_var_auth_user_id;
    dkd_var_next_status_key:='dkd_open'; dkd_var_next_status_title:='Yeni kullanıcı mesajı';
  end if;
  insert into public.dkd_support_messages(dkd_thread_id,dkd_user_id,dkd_sender_key,dkd_sender_title,dkd_message_text)
  values(dkd_var_thread_record.dkd_id,dkd_var_message_owner_id,dkd_var_sender_key,dkd_var_sender_title,dkd_var_clean_message_text)
  returning dkd_id into dkd_var_message_id;
  update public.dkd_support_threads set dkd_status_key=dkd_var_next_status_key,dkd_status_title=dkd_var_next_status_title,
    dkd_needs_admin_reply=not dkd_var_is_admin, dkd_admin_needed=not dkd_var_is_admin,
    dkd_last_message_text=left(dkd_var_clean_message_text,240),dkd_updated_at=now()
  where dkd_id=dkd_var_thread_record.dkd_id;
  return jsonb_build_object('dkd_ok',true,'dkd_thread_id',dkd_var_thread_record.dkd_id,'dkd_message_id',dkd_var_message_id,'dkd_sender_key',dkd_var_sender_key,'dkd_sender_title',dkd_var_sender_title);
end;
$function$;

-- Admin user search/detail/edit/delete.
create or replace function public.dkd_admin_user_search_dkd(dkd_param_search text default '', dkd_param_limit integer default 50)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','auth'
as $function$
declare dkd_result jsonb;
begin
  if not public.dkd_is_admin() then raise exception 'dkd_admin_required'; end if;
  select coalesce(jsonb_agg(to_jsonb(x) order by x.dkd_created_at desc),'[]'::jsonb) into dkd_result
  from (
    select u.id as dkd_user_id,u.email as dkd_email,u.phone as dkd_phone,u.created_at as dkd_created_at,u.last_sign_in_at as dkd_last_sign_in_at,
           p.nickname as dkd_nickname,p.dbg_id as dkd_dbg_id,p.avatar_image_url as dkd_avatar_image_url,p.courier_status as dkd_courier_status,p.dkd_city,p.dkd_region,
           p.courier_vehicle_type,p.courier_completed_jobs,p.dkd_courier_online,
           exists(select 1 from public.dkd_admin_users a where a.user_id=u.id) as dkd_is_admin
    from auth.users u
    left join public.dkd_profiles p on p.user_id=u.id
    where trim(coalesce(dkd_param_search,''))=''
       or u.id::text ilike '%'||trim(dkd_param_search)||'%'
       or coalesce(u.email,'') ilike '%'||trim(dkd_param_search)||'%'
       or coalesce(u.phone,'') ilike '%'||trim(dkd_param_search)||'%'
       or coalesce(p.nickname,'') ilike '%'||trim(dkd_param_search)||'%'
       or coalesce(p.dbg_id,'') ilike '%'||trim(dkd_param_search)||'%'
    order by u.created_at desc
    limit least(greatest(coalesce(dkd_param_limit,50),1),150)
  ) x;
  return dkd_result;
end;
$function$;

create or replace function public.dkd_admin_user_detail_dkd(dkd_param_user_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','auth'
as $function$
declare dkd_result jsonb; dkd_earnings jsonb;
begin
  if not public.dkd_is_admin() then raise exception 'dkd_admin_required'; end if;
  select jsonb_build_object(
    'dkd_user_id',u.id,'dkd_email',u.email,'dkd_phone',u.phone,'dkd_created_at',u.created_at,'dkd_updated_at',u.updated_at,'dkd_last_sign_in_at',u.last_sign_in_at,
    'dkd_email_confirmed_at',u.email_confirmed_at,'dkd_phone_confirmed_at',u.phone_confirmed_at,'dkd_raw_user_meta_data',u.raw_user_meta_data,
    'dkd_profile',coalesce(to_jsonb(p),'{}'::jsonb),
    'dkd_is_admin',exists(select 1 from public.dkd_admin_users ad where ad.user_id=u.id)
  ) into dkd_result
  from auth.users u left join public.dkd_profiles p on p.user_id=u.id where u.id=dkd_param_user_id;
  if dkd_result is null then raise exception 'dkd_user_not_found'; end if;
  dkd_earnings := public.dkd_courier_earnings_summary_dkd(dkd_param_user_id);
  return dkd_result || jsonb_build_object('dkd_earnings',dkd_earnings);
end;
$function$;

create or replace function public.dkd_admin_user_update_dkd(dkd_param_user_id uuid, dkd_param_patch jsonb)
returns jsonb
language plpgsql
security definer
set search_path to 'public','auth'
as $function$
declare dkd_patch jsonb := coalesce(dkd_param_patch,'{}'::jsonb); dkd_email text; dkd_phone text;
begin
  if not public.dkd_is_admin() then raise exception 'dkd_admin_required'; end if;
  if not exists(select 1 from auth.users where id=dkd_param_user_id) then raise exception 'dkd_user_not_found'; end if;
  if dkd_patch ? 'dkd_email' then
    dkd_email:=nullif(trim(dkd_patch->>'dkd_email'),'');
    if dkd_email is not null and exists(select 1 from auth.users where lower(email)=lower(dkd_email) and id<>dkd_param_user_id) then raise exception 'dkd_email_already_exists'; end if;
    update auth.users set email=dkd_email,updated_at=now() where id=dkd_param_user_id;
    update auth.identities set identity_data=jsonb_set(coalesce(identity_data,'{}'::jsonb),'{email}',to_jsonb(dkd_email),true),updated_at=now() where user_id=dkd_param_user_id and provider='email';
  end if;
  if dkd_patch ? 'dkd_phone' then
    dkd_phone:=nullif(trim(dkd_patch->>'dkd_phone'),'');
    if dkd_phone is not null and exists(select 1 from auth.users where phone=dkd_phone and id<>dkd_param_user_id) then raise exception 'dkd_phone_already_exists'; end if;
    update auth.users set phone=dkd_phone,updated_at=now() where id=dkd_param_user_id;
  end if;
  insert into public.dkd_profiles(user_id) values(dkd_param_user_id) on conflict(user_id) do nothing;
  update public.dkd_profiles set
    nickname=case when dkd_patch ? 'nickname' then nullif(trim(dkd_patch->>'nickname'),'') else nickname end,
    dbg_id=case when dkd_patch ? 'dbg_id' then nullif(trim(dkd_patch->>'dbg_id'),'') else dbg_id end,
    courier_status=case when dkd_patch ? 'courier_status' then nullif(lower(trim(dkd_patch->>'courier_status')),'') else courier_status end,
    courier_vehicle_type=case when dkd_patch ? 'courier_vehicle_type' then nullif(trim(dkd_patch->>'courier_vehicle_type'),'') else courier_vehicle_type end,
    courier_city=case when dkd_patch ? 'courier_city' then nullif(trim(dkd_patch->>'courier_city'),'') else courier_city end,
    courier_zone=case when dkd_patch ? 'courier_zone' then nullif(trim(dkd_patch->>'courier_zone'),'') else courier_zone end,
    dkd_country=case when dkd_patch ? 'dkd_country' then nullif(trim(dkd_patch->>'dkd_country'),'') else dkd_country end,
    dkd_city=case when dkd_patch ? 'dkd_city' then nullif(trim(dkd_patch->>'dkd_city'),'') else dkd_city end,
    dkd_region=case when dkd_patch ? 'dkd_region' then nullif(trim(dkd_patch->>'dkd_region'),'') else dkd_region end,
    courier_completed_jobs=case when dkd_patch ? 'courier_completed_jobs' then greatest(0,coalesce((dkd_patch->>'courier_completed_jobs')::int,0)) else courier_completed_jobs end,
    courier_active_days=case when dkd_patch ? 'courier_active_days' then greatest(0,coalesce((dkd_patch->>'courier_active_days')::int,0)) else courier_active_days end,
    courier_cancelled_jobs=case when dkd_patch ? 'courier_cancelled_jobs' then greatest(0,coalesce((dkd_patch->>'courier_cancelled_jobs')::int,0)) else courier_cancelled_jobs end,
    updated_at=now()
  where user_id=dkd_param_user_id;
  return public.dkd_admin_user_detail_dkd(dkd_param_user_id);
end;
$function$;

create or replace function public.dkd_admin_user_delete_dkd(dkd_param_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'public','auth'
as $function$
declare dkd_current_user_id uuid := auth.uid();
begin
  if not public.dkd_is_admin() then raise exception 'dkd_admin_required'; end if;
  if dkd_param_user_id is null then raise exception 'dkd_user_required'; end if;
  if dkd_param_user_id=dkd_current_user_id then raise exception 'dkd_cannot_delete_current_admin'; end if;
  delete from public.dkd_support_messages where dkd_user_id=dkd_param_user_id or dkd_thread_id in (select dkd_id from public.dkd_support_threads where dkd_user_id=dkd_param_user_id);
  delete from public.dkd_support_threads where dkd_user_id=dkd_param_user_id;
  delete from public.dkd_support_admin_queue where dkd_user_id=dkd_param_user_id;
  delete from public.dkd_courier_online_sessions where dkd_user_id=dkd_param_user_id;
  delete from public.dkd_courier_live_locations where user_id=dkd_param_user_id;
  delete from public.dkd_courier_jobs where customer_user_id=dkd_param_user_id or assigned_user_id=dkd_param_user_id;
  delete from public.dkd_cargo_shipments where customer_user_id=dkd_param_user_id or assigned_courier_user_id=dkd_param_user_id;
  delete from public.dkd_admin_users where user_id=dkd_param_user_id;
  delete from public.dkd_profiles where user_id=dkd_param_user_id;
  delete from auth.users where id=dkd_param_user_id;
  return jsonb_build_object('dkd_ok',true,'dkd_deleted_user_id',dkd_param_user_id);
end;
$function$;

grant execute on function public.dkd_admin_user_search_dkd(text,integer) to authenticated;
grant execute on function public.dkd_admin_user_detail_dkd(uuid) to authenticated;
grant execute on function public.dkd_admin_user_update_dkd(uuid,jsonb) to authenticated;
grant execute on function public.dkd_admin_user_delete_dkd(uuid) to authenticated;
