import React from 'react';
import { Linking, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { MaterialCommunityIcons } from '@expo/vector-icons';
const dkd_privacy_url_value='https://www.draborneagle.com/draborngo/privacy/';
const dkd_terms_url_value='https://www.draborneagle.com/draborngo/terms/';
const dkd_delete_url_value='https://www.draborneagle.com/draborngo/account-deletion/';
function DkdRow({icon,title,text}){return <View style={styles.row}><View style={styles.icon}><MaterialCommunityIcons name={icon} size={20} color="#9AF8FF"/></View><View style={{flex:1}}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowText}>{text}</Text></View></View>}
export default function DkdGooglePlayPolicyCenterModal({dkd_visible_value,dkd_on_close_value}){return <Modal visible={Boolean(dkd_visible_value)} animationType="slide" onRequestClose={dkd_on_close_value}><LinearGradient colors={['#030713','#071A2B','#140B2B']} style={styles.root}><View style={styles.header}><View style={{flex:1}}><Text style={styles.kicker}>GİZLİLİK VE VERİ MERKEZİ</Text><Text style={styles.title}>DraBornGo Veri Kontrolü</Text></View><Pressable onPress={dkd_on_close_value} style={styles.close}><MaterialCommunityIcons name="close" size={23} color="#FFF"/></Pressable></View><ScrollView contentContainerStyle={styles.content}><DkdRow icon="map-marker-radius-outline" title="Konum" text="Konum, yakın hizmet/kurye eşleşmeleri ve rota işlevleri için yalnız gerekli olduğunda kullanılır. Arka planda sürekli konum takibi amaçlanmaz."/><DkdRow icon="camera-outline" title="Kamera ve görseller" text="Kamera veya fotoğraf seçimi; profil görseli, belge/başvuru ve gerekli operasyon kanıtları için kullanıcı eylemiyle açılır."/><DkdRow icon="bell-outline" title="Bildirimler" text="Sipariş, kurye durumu, destek ve operasyon bildirimleri için izin istenir. Bildirim izni reddedilse de temel hesap erişimi devam eder."/><DkdRow icon="message-text-outline" title="Sosyal iletişim" text="DM ve ekip sohbetlerinde raporlama/moderasyon araçları bulunur. Kötüye kullanım içerikleri yönetim kuyruğuna iletilebilir."/><DkdRow icon="account-remove-outline" title="Hesap ve veri silme" text="Hesap silme talebi Profil ekranından başlatılabilir. Web üzerinde de bağımsız hesap silme başvuru sayfası bulunur."/><View style={styles.links}><Pressable onPress={()=>Linking.openURL(dkd_privacy_url_value)} style={styles.link}><Text style={styles.linkText}>Gizlilik Politikası</Text></Pressable><Pressable onPress={()=>Linking.openURL(dkd_terms_url_value)} style={styles.link}><Text style={styles.linkText}>Kullanım Şartları</Text></Pressable><Pressable onPress={()=>Linking.openURL(dkd_delete_url_value)} style={styles.link}><Text style={styles.linkText}>Hesap Silme</Text></Pressable></View></ScrollView></LinearGradient></Modal>}
const styles=StyleSheet.create({root:{flex:1,paddingTop:20},header:{padding:22,flexDirection:'row',alignItems:'center',gap:12},kicker:{color:'#67E8F9',fontSize:11,fontWeight:'900',letterSpacing:1.3},title:{color:'#FFF',fontSize:28,fontWeight:'900',marginTop:5},close:{width:48,height:48,borderRadius:16,backgroundColor:'rgba(255,255,255,0.07)',alignItems:'center',justifyContent:'center'},content:{padding:22,paddingTop:0,gap:12,paddingBottom:40},row:{borderRadius:22,borderWidth:1,borderColor:'rgba(123,230,255,0.16)',backgroundColor:'rgba(255,255,255,0.05)',padding:16,flexDirection:'row',gap:13},icon:{width:44,height:44,borderRadius:15,backgroundColor:'rgba(123,230,255,0.10)',alignItems:'center',justifyContent:'center'},rowTitle:{color:'#FFF',fontSize:16,fontWeight:'900'},rowText:{color:'rgba(235,241,255,0.70)',fontSize:13,lineHeight:19,marginTop:4},links:{gap:10,marginTop:6},link:{minHeight:54,borderRadius:18,backgroundColor:'#8CEEFF',alignItems:'center',justifyContent:'center'},linkText:{color:'#07111C',fontSize:15,fontWeight:'900'}});
